/**
 * SA466 — Disability Support Pension — Complete Field Map
 * 
 * Every question on the form in exact order, with correct PDF field names
 * and skip logic matching the form's "Go to Q__" instructions.
 * 
 * Skip logic source: PDF AcroForm GoTo button analysis (106 rules).
 */

export interface SA466Field {
  id: string;
  questionNumber: number;
  pageNumber: number;
  x: number; y: number;
  fieldType: "text" | "select" | "date";
  label: string;
  section: string;
  lumaQuestion: string;
  lumaExplanation?: string;
  options?: string[];
  required: boolean;
  skipText?: string;
  skipIfValues?: string[];
  maxWidth?: number;
  dateBoxes?: { ddX: number; ddY: number; mmX: number; mmY: number; yyyyX: number; yyyyY: number };
  tickPositions?: Record<string, { x: number; y: number }>;
  skipIf?: { field: string; equals: string; goTo: number };
  signatureNotice?: string;
  conditionalNotice?: { whenAnswer: string; notice: string }; // Extra Luma notice shown when answer matches
  pdfField?: string; // Named AcroForm field (primary)
  pdfFields?: string[]; // Multiple named fields
}

export interface SA466Section {
  id: string; title: string; startQ: number; endQ: number;
}

export const SA466_SECTIONS: SA466Section[] = [
  { id: "personal",   title: "Part A — Your Personal Details",       startQ: 1,   endQ: 21  },
  { id: "payment",    title: "Part B — Your Payment Details",        startQ: 22,  endQ: 37  },
  { id: "residence",  title: "Part C — Your Circumstances",          startQ: 38,  endQ: 53  },
  { id: "partner",    title: "Part G — Your Partner",                startQ: 54,  endQ: 80  },
  { id: "income",     title: "Part F — Income and Assets",           startQ: 81,  endQ: 127 },
  { id: "disability", title: "Part D — Your Disability or Medical Condition", startQ: 128, endQ: 142 },
  { id: "declaration",title: "Part H — Declaration",                 startQ: 143, endQ: 145 },
];

export const SA466_FIELDS: SA466Field[] = [

  // ═══════════════════════════════════════════════════════════════
  // PART A — PERSONAL DETAILS
  // ═══════════════════════════════════════════════════════════════

  { id: "crn", questionNumber: 1, pageNumber: 6, x: 50, y: 461,
    fieldType: "text", label: "Customer Reference Number", section: "personal",
    pdfFields: ["CRN.0","CRN.1","CRN.2","CRN.3"],
    lumaQuestion: "What is your Centrelink Customer Reference Number (CRN)? It's a 9 or 10-digit number. Say 'none' if you don't have one. 🔢",
    required: false, skipText: "none", maxWidth: 150 },

  { id: "title", questionNumber: 2, pageNumber: 6, x: 64, y: 412,
    fieldType: "select", label: "Title", section: "personal",
    pdfField: "Title1",
    options: ["Mr","Mrs","Miss","Ms","Mx","Dr","Other"],
    lumaQuestion: "What is your title? Mr, Mrs, Miss, Ms, Mx, Dr, or Other?",
    required: false,
    tickPositions: { "Mr":{x:64,y:412},"Mrs":{x:97,y:412},"Miss":{x:134,y:412},"Ms":{x:164,y:412},"Mx":{x:193,y:411} } },

  { id: "familyName", questionNumber: 2, pageNumber: 6, x: 51, y: 376,
    fieldType: "text", label: "Family Name", section: "personal",
    pdfField: "Q2.FamilyName",
    lumaQuestion: "What is your family name (surname)?", required: true, maxWidth: 220 },

  { id: "firstName", questionNumber: 2, pageNumber: 6, x: 51, y: 341,
    fieldType: "text", label: "First Name", section: "personal",
    pdfField: "Q2.FirstName",
    lumaQuestion: "What is your first name?", required: true, maxWidth: 220 },

  { id: "secondName", questionNumber: 2, pageNumber: 6, x: 51, y: 305,
    fieldType: "text", label: "Second Given Name", section: "personal",
    pdfField: "Q2.SecondName",
    lumaQuestion: "What is your middle name (second given name)? Say 'none' if you don't have one.",
    required: false, skipText: "none", maxWidth: 220 },

  { id: "dob", questionNumber: 3, pageNumber: 6, x: 52, y: 254,
    fieldType: "date", label: "Date of Birth", section: "personal",
    pdfFields: ["Q3.DateOfBirth.D","Q3.DateOfBirth.M","Q3.DateOfBirth.Y"],
    lumaQuestion: "What is your date of birth? Please type it as DD/MM/YYYY. For example: 15/03/1985 📅",
    required: true,
    dateBoxes: { ddX:52, ddY:254, mmX:85, mmY:254, yyyyX:120, yyyyY:254 } },

  { id: "otherNames", questionNumber: 4, pageNumber: 6, x: 339, y: 603,
    fieldType: "select", label: "Known By Other Names", section: "personal",
    options: ["Yes","No"],
    pdfField: "Q4",
    lumaQuestion: "Have you ever been known by any other name? For example, a name before marriage or a previous name.",
    required: false,
    tickPositions: { "Yes":{x:350,y:663}, "No":{x:350,y:679} } },

  { id: "otherNameDetails", questionNumber: 4, pageNumber: 6, x: 339, y: 603,
    fieldType: "text", label: "Other Name Details", section: "personal",
    pdfField: "Q4Details.0.OtherName",
    lumaQuestion: "What was your other name?",
    required: false, skipText: "none", maxWidth: 220,
    skipIf: { field: "otherNames", equals: "No", goTo: 5 } },

  { id: "gender", questionNumber: 5, pageNumber: 6, x: 379, y: 396,
    fieldType: "select", label: "Gender", section: "personal",
    pdfField: "Q5",
    options: ["Male","Female","Non-binary"],
    lumaQuestion: "What is your gender?", required: true,
    tickPositions: { "Male":{x:379,y:396}, "Female":{x:379,y:381}, "Non-binary":{x:379,y:365} } },

  { id: "permanentAddress", questionNumber: 6, pageNumber: 6, x: 335, y: 222,
    fieldType: "text", label: "Permanent Address", section: "personal",
    pdfFields: ["Q6.Address1","Q6.Address2","Q6.Address3"],
    lumaQuestion: "What is your permanent home address? Include street number, street name, suburb, and state. 🏠",
    required: true, maxWidth: 220 },

  { id: "postcode", questionNumber: 6, pageNumber: 6, x: 506, y: 182,
    fieldType: "text", label: "Postcode", section: "personal",
    pdfField: "Q6.Postcode",
    lumaQuestion: "What is your postcode?", required: true, maxWidth: 60 },

  { id: "postalAddressSame", questionNumber: 7, pageNumber: 6, x: 335, y: 160,
    fieldType: "select", label: "Postal Address Same", section: "personal",
    options: ["Yes","No"],
    lumaQuestion: "Is your postal address the same as your home address?", required: true,
    tickPositions: { "Yes":{x:335,y:160}, "No":{x:335,y:145} } },

  { id: "postalAddress", questionNumber: 7, pageNumber: 6, x: 335, y: 130,
    fieldType: "text", label: "Postal Address", section: "personal",
    pdfFields: ["Q7.Address1","Q7.Address2","Q7.Address3","Q7.Postcode"],
    lumaQuestion: "What is your postal address? Include suburb, state and postcode.",
    required: false, skipText: "same",
    skipIf: { field: "postalAddressSame", equals: "Yes", goTo: 8 } },

  { id: "homePhone", questionNumber: 8, pageNumber: 7, x: 89, y: 675,
    fieldType: "text", label: "Home Phone", section: "personal",
    pdfField: "Q8.PhoneNo",
    lumaQuestion: "What is your home phone number (including area code)? Say 'none' if you don't have one. 📞",
    required: false, skipText: "none", maxWidth: 150 },

  { id: "mobile", questionNumber: 8, pageNumber: 7, x: 143, y: 696,
    fieldType: "text", label: "Mobile Number", section: "personal",
    pdfField: "Q8.MobileNo",
    lumaQuestion: "What is your mobile phone number? Say 'none' if you don't have one. 📱",
    required: false, skipText: "none", maxWidth: 150 },

  { id: "email", questionNumber: 8, pageNumber: 7, x: 51, y: 660,
    fieldType: "text", label: "Email Address", section: "personal",
    pdfField: "Q8.Email",
    lumaQuestion: "What is your email address? Say 'none' if you don't have one. ✉️",
    required: false, skipText: "none", maxWidth: 250 },

  { id: "authorisePerson", questionNumber: 9, pageNumber: 7, x: 67, y: 575,
    fieldType: "select", label: "Authorise Person", section: "personal",
    pdfField: "Q9",
    options: ["Yes","No"],
    lumaQuestion: "Do you want to authorise another person or organisation to deal with Centrelink on your behalf? This is optional.",
    required: false,
    tickPositions: { "Yes":{x:67,y:575}, "No":{x:67,y:591} },
    conditionalNotice: {
      whenAnswer: "Yes",
      notice: "📋 Important: Since you want to authorise someone, you also need to complete a separate form — the SS313 (Authorising a person or organisation to enquire or act on your behalf).\n\nYou can do this online at servicesaustralia.gov.au/actforyou, or ask Centrelink for a paper copy.\n\nI've ticked Yes on your SA466. Let's continue with this form — we'll note that you need to complete the SS313 as well."
    } },

  // ─── Work History ───

  { id: "wasEmployee", questionNumber: 10, pageNumber: 7, x: 67, y: 405,
    fieldType: "select", label: "Was Employee", section: "personal",
    pdfField: "Q10",
    options: ["Yes","No"],
    lumaQuestion: "Before you needed to make this claim, were you working as an employee (not self-employed)? 💼",
    required: true,
    tickPositions: { "Yes":{x:67,y:390}, "No":{x:67,y:405} } },

  { id: "stillWorkingForEmployer", questionNumber: 12, pageNumber: 7, x: 67, y: 591,
    fieldType: "select", label: "Still Working For Employer", section: "personal",
    pdfField: "Q12",
    options: ["Yes","No"],
    lumaQuestion: "Are you still working for that employer now?",
    required: false,
    skipIf: { field: "wasEmployee", equals: "No", goTo: 16 },
    tickPositions: { "Yes":{x:67,y:575}, "No":{x:67,y:591} } },

  { id: "currentHoursWorking", questionNumber: 12, pageNumber: 7, x: 143, y: 550,
    fieldType: "text", label: "Current Hours Working", section: "personal",
    lumaQuestion: "How many hours per week are you working now?",
    required: false, skipText: "none", maxWidth: 80,
    skipIf: { field: "stillWorkingForEmployer", equals: "No", goTo: 13 } },

  { id: "gradualReturnToWork", questionNumber: 13, pageNumber: 7, x: 350, y: 705,
    fieldType: "select", label: "Gradual Return To Work", section: "personal",
    pdfField: "Q13",
    options: ["Yes","No"],
    lumaQuestion: "Is this a gradual return to work program?",
    required: false,
    skipIf: { field: "stillWorkingForEmployer", equals: "No", goTo: 14 },
    tickPositions: { "Yes":{x:350,y:690}, "No":{x:350,y:705} } },

  { id: "planningLessHours", questionNumber: 14, pageNumber: 7, x: 350, y: 779,
    fieldType: "select", label: "Planning Less Hours", section: "personal",
    pdfField: "Q14",
    options: ["Yes","No"],
    lumaQuestion: "Are you planning to work fewer hours because of your disability or medical condition?",
    required: false,
    skipIf: { field: "wasEmployee", equals: "No", goTo: 16 },
    tickPositions: { "Yes":{x:350,y:763}, "No":{x:350,y:779} } },

  { id: "riskLosingJob", questionNumber: 15, pageNumber: 7, x: 350, y: 190,
    fieldType: "select", label: "Risk of Losing Job", section: "personal",
    pdfField: "Q15",
    options: ["Yes","No"],
    lumaQuestion: "Are you at risk of losing your job because of your disability or medical condition?",
    required: false,
    skipIf: { field: "wasEmployee", equals: "No", goTo: 16 },
    tickPositions: { "Yes":{x:350,y:174}, "No":{x:350,y:190} } },

  { id: "wasSelfEmployed", questionNumber: 16, pageNumber: 7, x: 67, y: 194,
    fieldType: "select", label: "Was Self-Employed", section: "personal",
    pdfField: "Q16",
    options: ["Yes","No"],
    lumaQuestion: "Before this claim, were you self-employed, a contractor, or a primary producer (farmer/fisher)?",
    required: false,
    tickPositions: { "Yes":{x:67,y:179}, "No":{x:67,y:194} } },

  { id: "stillSelfEmployed", questionNumber: 17, pageNumber: 7, x: 67, y: 109,
    fieldType: "select", label: "Still Self-Employed", section: "personal",
    pdfField: "Q17",
    options: ["Yes","No"],
    lumaQuestion: "Are you still doing this self-employed work now?",
    required: false,
    skipIf: { field: "wasSelfEmployed", equals: "No", goTo: 18 },
    tickPositions: { "Yes":{x:67,y:93}, "No":{x:67,y:109} } },

  { id: "wasApprentice", questionNumber: 18, pageNumber: 7, x: 350, y: 448,
    fieldType: "select", label: "Australian Apprentice", section: "personal",
    pdfField: "Q18",
    options: ["Yes","No"],
    lumaQuestion: "Before this claim, were you a full-time Australian Apprentice or Trainee?",
    required: false,
    tickPositions: { "Yes":{x:350,y:432}, "No":{x:350,y:448} } },

  { id: "stillAtSchool", questionNumber: 19, pageNumber: 7, x: 350, y: 253,
    fieldType: "select", label: "Still At School", section: "personal",
    pdfField: "Q19",
    options: ["Yes","No"],
    lumaQuestion: "Are you still attending secondary school?",
    required: false,
    tickPositions: { "Yes":{x:350,y:188}, "No":{x:350,y:253} } },

  { id: "doingStudy", questionNumber: 20, pageNumber: 8, x: 67, y: 763,
    fieldType: "select", label: "Doing Other Study", section: "personal",
    pdfField: "Q20",
    options: ["Yes","No"],
    lumaQuestion: "Are you currently doing study at TAFE, university or another institution?",
    required: false,
    tickPositions: { "Yes":{x:67,y:763}, "No":{x:67,y:779} } },

  { id: "studyHours", questionNumber: 20, pageNumber: 8, x: 52, y: 612,
    fieldType: "text", label: "Study Hours Per Week", section: "personal",
    pdfField: "20.D.Hours",
    lumaQuestion: "How many hours per week are you studying?",
    required: false, skipText: "none", maxWidth: 80,
    skipIf: { field: "doingStudy", equals: "No", goTo: 21 } },

  { id: "activityBeforeClaim", questionNumber: 21, pageNumber: 8, x: 51, y: 430,
    fieldType: "text", label: "Activity Before Claim", section: "personal",
    lumaQuestion: "Before this claim, what were you mainly doing? For example: looking after children, unemployed, caring for someone, voluntary work, recovering from illness. Say 'none' if not applicable.",
    required: false, skipText: "none", maxWidth: 350 },

  { id: "chargedWithOffence", questionNumber: 22, pageNumber: 8, x: 67, y: 207,
    fieldType: "select", label: "Charged With Offence", section: "personal",
    pdfField: "Q22",
    options: ["Yes","No"],
    lumaQuestion: "Have you been charged with a criminal offence and are currently in custody, on remand, or under psychiatric confinement?",
    required: false,
    tickPositions: { "Yes":{x:67,y:191}, "No":{x:67,y:207} },
    conditionalNotice: {
      whenAnswer: "Yes",
      notice: "⚠️ Important — Eligibility Warning: You may not be eligible for the Disability Support Pension while in custody or under psychiatric confinement.\n\nBefore completing this form, please call Centrelink on 132 717 to discuss your options.\n\nI've noted your answer and we can continue, but please make that call as soon as possible."
    } },

  { id: "institutionName", questionNumber: 23, pageNumber: 8, x: 334, y: 151,
    fieldType: "text", label: "Institution Name", section: "personal",
    pdfField: "Q23",
    lumaQuestion: "What is the name of the institution where you are detained?",
    required: false, skipText: "none", maxWidth: 250,
    skipIf: { field: "chargedWithOffence", equals: "No", goTo: 25 } },

  { id: "releaseDate", questionNumber: 24, pageNumber: 8, x: 333, y: 301,
    fieldType: "date", label: "Expected Release Date", section: "personal",
    pdfFields: ["Q24.D","Q24.M","Q24.Y"],
    lumaQuestion: "What is your expected release date? (DD/MM/YYYY, or say 'unknown')",
    required: false, skipText: "unknown",
    dateBoxes: { ddX:333, ddY:301, mmX:367, mmY:302, yyyyX:401, yyyyY:301 },
    skipIf: { field: "chargedWithOffence", equals: "No", goTo: 25 } },

  // ═══════════════════════════════════════════════════════════════
  // PART B — PAYMENT DETAILS (Q25-Q37)
  // ═══════════════════════════════════════════════════════════════

  { id: "claimingForBlindness", questionNumber: 25, pageNumber: 8, x: 350, y: 791,
    fieldType: "select", label: "Claiming For Blindness", section: "payment",
    pdfField: "Q25",
    options: ["Yes","No"],
    lumaQuestion: "Are you claiming DSP because you are permanently blind?",
    lumaExplanation: "Permanently blind means visual acuity less than 6/60 in both eyes after correction, or constriction within 10 degrees of fixation.",
    required: false,
    tickPositions: { "Yes":{x:350,y:775}, "No":{x:350,y:791} } },

  { id: "claimingRentAssistance", questionNumber: 26, pageNumber: 8, x: 350, y: 729,
    fieldType: "select", label: "Claiming Rent Assistance", section: "payment",
    pdfField: "Q26",
    options: ["Yes","No"],
    lumaQuestion: "Are you (or your partner) claiming Rent Assistance with this application?",
    required: false,
    tickPositions: { "Yes":{x:350,y:713}, "No":{x:350,y:729} },
    conditionalNotice: {
      whenAnswer: "Yes",
      notice: "📋 Extra form needed: Since you're claiming Rent Assistance, you'll need to complete and return the Income and Assets form (SA369).\n\nDownload it at servicesaustralia.gov.au/forms or ask Centrelink for a paper copy.\n\nI'll add this to your checklist at the end."
    } },

  { id: "gettingNZPayment", questionNumber: 27, pageNumber: 8, x: 350, y: 585,
    fieldType: "select", label: "Getting NZ Payment", section: "payment",
    pdfField: "Q27",
    options: ["Yes","No"],
    lumaQuestion: "Are you (or your partner) getting a New Zealand government payment?",
    required: false,
    tickPositions: { "Yes":{x:350,y:569}, "No":{x:350,y:585} } },

  { id: "gettingDVAPayment", questionNumber: 28, pageNumber: 8, x: 350, y: 532,
    fieldType: "select", label: "Getting DVA Payment", section: "payment",
    pdfField: "Q28",
    options: ["Yes","No"],
    lumaQuestion: "Are you (or your partner) getting a payment from the Department of Veterans' Affairs (DVA)?",
    required: false,
    tickPositions: { "Yes":{x:350,y:517}, "No":{x:350,y:532} },
    conditionalNotice: {
      whenAnswer: "Yes",
      notice: "📄 Document needed: You'll need to attach a letter or document showing the reference number and details of each DVA payment.\n\nIf you don't have this, contact the Department of Veterans' Affairs on 1800 838 372.\n\nI'll add this to your checklist at the end."
    } },

  { id: "selfEmploymentAssistance", questionNumber: 29, pageNumber: 8, x: 350, y: 448,
    fieldType: "select", label: "Self Employment Assistance", section: "payment",
    pdfField: "Q29",
    options: ["Yes","No"],
    lumaQuestion: "Are you (or your partner) getting Self-Employment Assistance payments?",
    required: false,
    tickPositions: { "Yes":{x:350,y:432}, "No":{x:350,y:448} },
    conditionalNotice: {
      whenAnswer: "Yes",
      notice: "📄 Document needed: You'll need to attach a letter or document showing the reference number and details of each Self-Employment Assistance payment.\n\nContact your provider if you don't have this document.\n\nI'll add this to your checklist at the end."
    } },

  { id: "gettingWorkersComp", questionNumber: 30, pageNumber: 9, x: 67, y: 548,
    fieldType: "select", label: "Getting Workers Compensation", section: "payment",
    pdfField: "Q30",
    options: ["Yes","No"],
    lumaQuestion: "Are you (or your partner) getting, or do you have a claim for, workers compensation, damages, or any other compensation? 💰",
    required: false,
    tickPositions: { "Yes":{x:67,y:548}, "No":{x:67,y:564} } },

  { id: "incomeStreamToldBefore", questionNumber: 31, pageNumber: 9, x: 67, y: 422,
    fieldType: "select", label: "Income Stream Told Before", section: "payment",
    pdfField: "Q31",
    options: ["Yes","No"],
    lumaQuestion: "Have you (or your partner) told Centrelink about this compensation before?",
    required: false,
    skipIf: { field: "gettingWorkersComp", equals: "No", goTo: 32 },
    tickPositions: { "Yes":{x:67,y:422}, "No":{x:67,y:500} },
    conditionalNotice: {
      whenAnswer: "No",
      notice: "📋 Extra form needed: Since Centrelink hasn't been told about this compensation before, you'll need to complete and return a Compensation and Damages form (Mod C).\n\nDownload it at servicesaustralia.gov.au/forms or ask Centrelink for a copy.\n\nI'll add this to your checklist at the end."
    } },

  { id: "gettingIncomeStream", questionNumber: 32, pageNumber: 9, x: 67, y: 346,
    fieldType: "select", label: "Getting Income Stream", section: "payment",
    pdfField: "Q32",
    options: ["Yes","No"],
    lumaQuestion: "Are you (or your partner) getting payments from an income stream product? For example, a superannuation pension or annuity.",
    required: false,
    tickPositions: { "Yes":{x:67,y:346}, "No":{x:67,y:362} } },

  { id: "bankName", questionNumber: 34, pageNumber: 10, x: 51, y: 427,
    fieldType: "text", label: "Bank Name", section: "payment",
    pdfField: "BankName",
    lumaQuestion: "What is the name of your bank or financial institution where you want your payment? For example: Commonwealth Bank, ANZ, Westpac. 🏦",
    required: true, maxWidth: 220 },

  { id: "bsb", questionNumber: 34, pageNumber: 10, x: 50, y: 392,
    fieldType: "text", label: "BSB Number", section: "payment",
    pdfField: "BSB",
    lumaQuestion: "What is your BSB number? It's a 6-digit number. For example: 062000",
    required: true, maxWidth: 80 },

  { id: "accountNumber", questionNumber: 34, pageNumber: 10, x: 51, y: 356,
    fieldType: "text", label: "Account Number", section: "payment",
    pdfField: "ACCNo",
    lumaQuestion: "What is your bank account number?",
    required: true, maxWidth: 150 },

  { id: "accountName", questionNumber: 34, pageNumber: 10, x: 51, y: 320,
    fieldType: "text", label: "Account Holder Name (First)", section: "payment",
    pdfField: "AccNames",
    lumaQuestion: "What name is on the bank account? Usually your full name.",
    required: true, maxWidth: 220 },

  { id: "accountName2", questionNumber: 34, pageNumber: 10, x: 51, y: 308,
    fieldType: "text", label: "Account Holder Name (Second)", section: "payment",
    pdfField: "AccNames",
    lumaQuestion: "Is there a second account holder? If yes, give their full name. Say 'none' if it's just your account.",
    required: false, skipText: "none", maxWidth: 220 },

  { id: "receivingOtherPayments", questionNumber: 35, pageNumber: 10, x: 350, y: 565,
    fieldType: "select", label: "Receiving Other Payments", section: "payment",
    pdfField: "Q35",
    options: ["Yes","No"],
    lumaQuestion: "Are you (or your partner) currently getting any government payments? For example: JobSeeker, Youth Allowance, Carer Payment, Age Pension.",
    required: false,
    tickPositions: { "Yes":{x:350,y:565}, "No":{x:350,y:581} },
    conditionalNotice: {
      whenAnswer: "No",
      notice: "📋 Extra form needed: Since you're not currently getting a Centrelink income support payment, you'll also need to complete and return the Income and Assets form (SA369).\n\nDownload it at servicesaustralia.gov.au/forms or ask Centrelink for a paper copy.\n\nI'll add this to your checklist at the end."
    } },

  { id: "changedCircumstances", questionNumber: 36, pageNumber: 10, x: 350, y: 515,
    fieldType: "select", label: "Changed Circumstances", section: "payment",
    pdfField: "Q36",
    options: ["Yes","No"],
    lumaQuestion: "Are there any changes to your (or your partner's) circumstances that Centrelink needs to know about?",
    required: false,
    tickPositions: { "Yes":{x:350,y:499}, "No":{x:350,y:515} } },

  { id: "youngerThan21ForPayment", questionNumber: 37, pageNumber: 10, x: 350, y: 485,
    fieldType: "select", label: "Younger Than 21", section: "payment",
    pdfField: "Q37",
    options: ["Yes","No"],
    lumaQuestion: "Are you younger than 21 years old? (This affects your payment rate)",
    required: false,
    tickPositions: { "Yes":{x:350,y:470}, "No":{x:350,y:485} } },

  // ═══════════════════════════════════════════════════════════════
  // PART C — CIRCUMSTANCES / RESIDENCE (Q38-Q53)
  // ═══════════════════════════════════════════════════════════════

  { id: "interpreterNeeded", questionNumber: 38, pageNumber: 11, x: 67, y: 531,
    fieldType: "select", label: "Interpreter Needed", section: "residence",
    pdfField: "Q38",
    options: ["Yes","No"],
    lumaQuestion: "Do you need an interpreter to speak with Centrelink? 🗣️",
    required: false,
    tickPositions: { "Yes":{x:67,y:515}, "No":{x:67,y:531} } },

  { id: "preferredLanguage", questionNumber: 39, pageNumber: 11, x: 51, y: 463,
    fieldType: "text", label: "Preferred Spoken Language", section: "residence",
    pdfField: "Q39",
    lumaQuestion: "What is your preferred spoken language?",
    required: false, skipText: "English", maxWidth: 220,
    skipIf: { field: "interpreterNeeded", equals: "No", goTo: 40 } },

  { id: "preferredWrittenLanguage", questionNumber: 40, pageNumber: 11, x: 51, y: 409,
    fieldType: "text", label: "Preferred Written Language", section: "residence",
    pdfField: "Q40",
    lumaQuestion: "What is your preferred written language?",
    required: false, skipText: "English", maxWidth: 220,
    skipIf: { field: "interpreterNeeded", equals: "No", goTo: 44 } },

  { id: "travelledOverseas", questionNumber: 44, pageNumber: 11, x: 67, y: 515,
    fieldType: "select", label: "Travelled Overseas", section: "residence",
    pdfField: "Q44",
    options: ["Yes","No"],
    lumaQuestion: "Have you ever travelled outside Australia, including short trips? ✈️",
    required: false,
    tickPositions: { "Yes":{x:67,y:515}, "No":{x:67,y:531} } },

  { id: "australianCitizenBornHere", questionNumber: 45, pageNumber: 11, x: 67, y: 62,
    fieldType: "select", label: "Australian Citizen Born Here", section: "residence",
    pdfField: "Q45",
    options: ["Yes","No"],
    lumaQuestion: "Are you an Australian citizen who was born in Australia? 🇦🇺",
    required: true,
    tickPositions: { "Yes":{x:67,y:62}, "No":{x:67,y:78} } },

  { id: "countryOfBirth", questionNumber: 46, pageNumber: 11, x: 335, y: 447,
    fieldType: "text", label: "Country of Birth", section: "residence",
    pdfField: "Q46",
    lumaQuestion: "What is your country of birth?",
    required: false, skipText: "Australia", maxWidth: 200,
    skipIf: { field: "australianCitizenBornHere", equals: "Yes", goTo: 47 } },

  { id: "australianCitizen", questionNumber: 47, pageNumber: 11, x: 371, y: 687,
    fieldType: "select", label: "Australian Citizen", section: "residence",
    pdfField: "Q47",
    options: ["Yes","No"],
    lumaQuestion: "Are you an Australian citizen?",
    required: true,
    tickPositions: { "Yes":{x:371,y:687}, "No":{x:371,y:672} } },

  { id: "countryOfCitizenship", questionNumber: 47, pageNumber: 11, x: 335, y: 447,
    fieldType: "text", label: "Country of Citizenship", section: "residence",
    pdfField: "Q47Details.CoC",
    lumaQuestion: "What is your country of citizenship?",
    required: false, maxWidth: 200,
    skipIf: { field: "australianCitizen", equals: "Yes", goTo: 53 } },

  { id: "permanentResident", questionNumber: 48, pageNumber: 12, x: 138, y: 792,
    fieldType: "select", label: "Permanent Resident", section: "residence",
    pdfField: "Q48",
    options: ["Permanent","Temporary","NZ citizen","Not sure"],
    lumaQuestion: "What type of visa do you have?",
    required: false,
    skipIf: { field: "australianCitizen", equals: "Yes", goTo: 53 },
    tickPositions: { "Permanent":{x:138,y:792},"Temporary":{x:138,y:776},"NZ citizen":{x:138,y:761},"Not sure":{x:138,y:734} } },

  { id: "visaType", questionNumber: 49, pageNumber: 12, x: 51, y: 670,
    fieldType: "text", label: "Visa Class on Arrival", section: "residence",
    pdfField: "Q49.VisaClass",
    lumaQuestion: "What type of visa did you arrive in Australia on? For example: '309', '820', or 'Working Holiday'.",
    required: false, skipText: "not sure", maxWidth: 150,
    skipIf: { field: "australianCitizen", equals: "Yes", goTo: 53 } },

  { id: "visaChanged", questionNumber: 50, pageNumber: 12, x: 67, y: 605,
    fieldType: "select", label: "Visa Changed", section: "residence",
    pdfField: "Q50",
    options: ["Yes","No"],
    lumaQuestion: "Has your visa changed since you arrived in Australia?",
    required: false,
    skipIf: { field: "australianCitizen", equals: "Yes", goTo: 53 },
    tickPositions: { "Yes":{x:67,y:605}, "No":{x:67,y:621} } },

  { id: "livedBefor1965", questionNumber: 51, pageNumber: 12, x: 67, y: 521,
    fieldType: "select", label: "Lived In Australia Before 1965", section: "residence",
    pdfField: "Q51",
    options: ["Yes","No"],
    lumaQuestion: "Did you start living in Australia before 1965?",
    required: false,
    skipIf: { field: "australianCitizen", equals: "Yes", goTo: 53 },
    tickPositions: { "Yes":{x:67,y:505}, "No":{x:67,y:521} } },

  { id: "assuranceOfSupport", questionNumber: 52, pageNumber: 12, x: 84, y: 270,
    fieldType: "select", label: "Assurance of Support", section: "residence",
    pdfField: "Q52",
    options: ["Yes","No","Not sure"],
    lumaQuestion: "Did someone provide you with an assurance of support when you came to Australia? This is a legal commitment by a sponsor to support you financially.",
    required: false,
    skipIf: { field: "australianCitizen", equals: "Yes", goTo: 54 },
    tickPositions: { "Yes":{x:84,y:270},"No":{x:84,y:301},"Not sure":{x:84,y:286} } },

  { id: "overseasTravelDetails", questionNumber: 53, pageNumber: 12, x: 84, y: 724,
    fieldType: "select", label: "Overseas Travel Details", section: "residence",
    pdfField: "Q53",
    options: ["Yes","No"],
    lumaQuestion: "Have you ever lived outside Australia for more than 12 months in a row?",
    required: false,
    tickPositions: { "Yes":{x:350,y:708}, "No":{x:350,y:724} } },

  // ═══════════════════════════════════════════════════════════════
  // PART G — YOUR PARTNER (Q54-Q80)
  // Q54 No → Go to Q77
  // Q62 Yes → Go to Q67 (skip partner address questions)
  // Q73 Yes → Go to Q81
  // ═══════════════════════════════════════════════════════════════

  { id: "hasPartner", questionNumber: 54, pageNumber: 13, x: 67, y: 762,
    fieldType: "select", label: "Have a Partner", section: "partner",
    pdfField: "Q54",
    options: ["Yes","No"],
    lumaQuestion: "Do you have a partner? This means a husband, wife, or de facto partner that you live with or have a relationship with. 👫",
    lumaExplanation: "A de facto partner is someone you live with in a relationship, even if you are not married.",
    required: true,
    tickPositions: { "Yes":{x:67,y:747}, "No":{x:67,y:762} } },

  { id: "relationshipStatus", questionNumber: 55, pageNumber: 13, x: 140, y: 579,
    fieldType: "select", label: "Relationship Type", section: "partner",
    pdfField: "Q55",
    options: ["Married","De facto","Registered relationship"],
    lumaQuestion: "What is your relationship with your partner?",
    required: false,
    skipIf: { field: "hasPartner", equals: "No", goTo: 77 },
    tickPositions: { "Married":{x:140,y:579},"De facto":{x:140,y:447},"Registered relationship":{x:140,y:512} } },

  { id: "partnerCrn", questionNumber: 56, pageNumber: 13, x: 50, y: 334,
    fieldType: "text", label: "Partner CRN", section: "partner",
    pdfFields: ["CRN.Partner.0","CRN.Partner.1","CRN.Partner.2","CRN.Partner.3"],
    lumaQuestion: "Does your partner have a Centrelink Customer Reference Number (CRN)? If so, what is it? Say 'none' if not.",
    required: false, skipText: "none",
    skipIf: { field: "hasPartner", equals: "No", goTo: 77 } },

  { id: "partnerFamilyName", questionNumber: 57, pageNumber: 13, x: 51, y: 249,
    fieldType: "text", label: "Partner Family Name", section: "partner",
    pdfField: "Partner_FamilyName",
    lumaQuestion: "What is your partner's family name (surname)?",
    required: false, maxWidth: 200,
    skipIf: { field: "hasPartner", equals: "No", goTo: 77 } },

  { id: "partnerFirstName", questionNumber: 57, pageNumber: 13, x: 51, y: 213,
    fieldType: "text", label: "Partner First Name", section: "partner",
    pdfField: "Partner_FirstName",
    lumaQuestion: "What is your partner's first name?",
    required: false, maxWidth: 200,
    skipIf: { field: "hasPartner", equals: "No", goTo: 77 } },

  { id: "partnerDob", questionNumber: 58, pageNumber: 13, x: 49, y: 125,
    fieldType: "date", label: "Partner Date of Birth", section: "partner",
    pdfFields: ["Q58.D","Q58.M","Q58.Y"],
    lumaQuestion: "What is your partner's date of birth? (DD/MM/YYYY)",
    required: false,
    dateBoxes: { ddX:49, ddY:125, mmX:83, mmY:125, yyyyX:118, yyyyY:125 },
    skipIf: { field: "hasPartner", equals: "No", goTo: 77 } },

  { id: "partnerAuthorisation", questionNumber: 59, pageNumber: 13, x: 350, y: 749,
    fieldType: "select", label: "Partner Authorisation", section: "partner",
    pdfField: "Q59",
    options: ["Yes","No"],
    lumaQuestion: "Do you give permission for your partner to speak to Centrelink on your behalf?",
    required: false,
    skipIf: { field: "hasPartner", equals: "No", goTo: 77 },
    tickPositions: { "Yes":{x:350,y:749}, "No":{x:350,y:765} } },

  { id: "partnerGender", questionNumber: 61, pageNumber: 13, x: 379, y: 337,
    fieldType: "select", label: "Partner Gender", section: "partner",
    pdfField: "Q61",
    options: ["Male","Female","Non-binary"],
    lumaQuestion: "What is your partner's gender?",
    required: false,
    skipIf: { field: "hasPartner", equals: "No", goTo: 77 },
    tickPositions: { "Male":{x:379,y:337},"Female":{x:379,y:321},"Non-binary":{x:379,y:306} } },

  { id: "liveWithPartner", questionNumber: 62, pageNumber: 13, x: 351, y: 624,
    fieldType: "select", label: "Live With Partner", section: "partner",
    pdfField: "Q62",
    options: ["Yes","No"],
    lumaQuestion: "Do you currently live in the same home as your partner?",
    required: false,
    skipIf: { field: "hasPartner", equals: "No", goTo: 77 },
    tickPositions: { "Yes":{x:350,y:609}, "No":{x:351,y:624} } },

  { id: "partnerAddress", questionNumber: 63, pageNumber: 13, x: 335, y: 192,
    fieldType: "text", label: "Partner Permanent Address", section: "partner",
    pdfFields: ["Q63.Address1","Q63.Address2","Q63.Address3","Q63.Postcode"],
    lumaQuestion: "What is your partner's permanent address?",
    required: false, skipText: "same", maxWidth: 350,
    skipIf: { field: "liveWithPartner", equals: "Yes", goTo: 67 } },

  { id: "reasonNotWithPartner", questionNumber: 65, pageNumber: 14, x: 135, y: 728,
    fieldType: "select", label: "Reason Not Living With Partner", section: "partner",
    pdfField: "Q65",
    options: ["Partner illness","Your illness","Partner in prison","Partner employment","Other"],
    lumaQuestion: "Why are you not living with your partner?",
    required: false,
    skipIf: { field: "liveWithPartner", equals: "Yes", goTo: 67 },
    tickPositions: { "Partner illness":{x:135,y:791},"Your illness":{x:135,y:775},"Partner in prison":{x:135,y:760},"Partner employment":{x:135,y:744},"Other":{x:135,y:728} } },

  { id: "partnerGettingPayments", questionNumber: 67, pageNumber: 14, x: 350, y: 790,
    fieldType: "select", label: "Partner Getting Payments", section: "partner",
    pdfField: "Q67",
    options: ["Yes","No"],
    lumaQuestion: "In the last 14 days, has your partner received any Centrelink, DVA, NZ, or compensation payments?",
    required: false,
    skipIf: { field: "hasPartner", equals: "No", goTo: 77 },
    tickPositions: { "Yes":{x:350,y:712}, "No":{x:350,y:790} } },

  { id: "partnerLivedInAustralia", questionNumber: 73, pageNumber: 14, x: 350, y: 435,
    fieldType: "select", label: "Partner Lived In Australia", section: "partner",
    pdfField: "Q73",
    options: ["Yes","No"],
    lumaQuestion: "Has your partner ever lived in Australia?",
    required: false,
    skipIf: { field: "hasPartner", equals: "No", goTo: 77 },
    tickPositions: { "Yes":{x:350,y:419}, "No":{x:350,y:435} } },

  { id: "partnerCountryOfBirth", questionNumber: 71, pageNumber: 14, x: 335, y: 661,
    fieldType: "text", label: "Partner Country of Birth", section: "partner",
    pdfField: "Q71",
    lumaQuestion: "What is your partner's country of birth?",
    required: false, skipText: "Australia", maxWidth: 200,
    skipIf: { field: "hasPartner", equals: "No", goTo: 77 } },

  { id: "partnerAustralianCitizen", questionNumber: 72, pageNumber: 14, x: 371, y: 612,
    fieldType: "select", label: "Partner Australian Citizen", section: "partner",
    pdfField: "Q72",
    options: ["Yes","No"],
    lumaQuestion: "Is your partner an Australian citizen?",
    required: false,
    skipIf: { field: "hasPartner", equals: "No", goTo: 77 },
    tickPositions: { "Yes":{x:371,y:612}, "No":{x:371,y:627} } },

  { id: "partnerVisaType", questionNumber: 74, pageNumber: 14, x: 422, y: 374,
    fieldType: "select", label: "Partner Visa Type", section: "partner",
    pdfField: "Q74",
    options: ["Permanent","Temporary","NZ citizen","Not sure"],
    lumaQuestion: "What type of visa does your partner have?",
    required: false,
    skipIf: { field: "partnerAustralianCitizen", equals: "Yes", goTo: 77 },
    tickPositions: { "Permanent":{x:422,y:374},"Temporary":{x:422,y:358},"NZ citizen":{x:421,y:342},"Not sure":{x:421,y:315} } },

  // Q77 — Current relationship status (if no current partner)
  { id: "currentRelationshipStatus", questionNumber: 77, pageNumber: 15, x: 424, y: 703,
    fieldType: "select", label: "Current Relationship Status", section: "partner",
    pdfField: "Q77",
    options: ["Separated","Divorced","Widowed","Never had a partner"],
    lumaQuestion: "You said you don't currently have a partner. Which of these describes your situation?",
    required: false,
    skipIf: { field: "hasPartner", equals: "Yes", goTo: 81 },
    tickPositions: { "Separated":{x:424,y:703},"Divorced":{x:424,y:639},"Widowed":{x:424,y:584},"Never had a partner":{x:424,y:520} } },

  { id: "deceasedPartnerName", questionNumber: 78, pageNumber: 15, x: 340, y: 439,
    fieldType: "text", label: "Deceased Partner Name", section: "partner",
    pdfField: "Q78.FullName",
    lumaQuestion: "What was your late partner's full name?",
    required: false, skipText: "none", maxWidth: 220,
    skipIf: { field: "currentRelationshipStatus", equals: "Never had a partner", goTo: 81 } },

  { id: "exPartnerFamilyName", questionNumber: 79, pageNumber: 15, x: 335, y: 333,
    fieldType: "text", label: "Ex-Partner Family Name", section: "partner",
    pdfField: "Q79.FamilyName",
    lumaQuestion: "What is your ex-partner's family name?",
    required: false, skipText: "none", maxWidth: 200,
    skipIf: { field: "hasPartner", equals: "Yes", goTo: 81 } },

  { id: "exPartnerAddress", questionNumber: 80, pageNumber: 15, x: 335, y: 208,
    fieldType: "text", label: "Ex-Partner Address", section: "partner",
    pdfFields: ["Q80.Address1","Q80.Address2","Q80.Address3"],
    lumaQuestion: "What is your ex-partner's current address (if known)? Say 'unknown' if you don't know.",
    required: false, skipText: "unknown",
    skipIf: { field: "hasPartner", equals: "Yes", goTo: 81 } },

  // ═══════════════════════════════════════════════════════════════
  // PART F — INCOME AND ASSETS (Q81-Q127)
  // ═══════════════════════════════════════════════════════════════

  { id: "shareAccommodation", questionNumber: 81, pageNumber: 16, x: 67, y: 700,
    fieldType: "select", label: "Share Accommodation", section: "income",
    pdfField: "Q81",
    options: ["Yes","No"],
    lumaQuestion: "Do you share your home with anyone other than an immediate family member? (Housemates, boarders, non-family members) 🏠",
    required: true,
    tickPositions: { "Yes":{x:67,y:684}, "No":{x:67,y:700} } },

  { id: "ownHomeNotLiving", questionNumber: 83, pageNumber: 18, x: 67, y: 765,
    fieldType: "select", label: "Own Home Not Living In", section: "income",
    pdfField: "Q83",
    options: ["Yes","No"],
    lumaQuestion: "Do you (or your partner) own a home that you are NOT currently living in? For example, a rental property or a home you own but don't live in. 🏡",
    required: true,
    tickPositions: { "Yes":{x:67,y:750}, "No":{x:67,y:765} } },

  { id: "whyNotInOwnHome", questionNumber: 84, pageNumber: 18, x: 180, y: 693,
    fieldType: "select", label: "Why Not In Own Home", section: "income",
    pdfField: "Q84.Reason",
    options: ["Study","Medical treatment","Receiving care at someone's home","Receiving care in nursing home","Providing care","Overseas","Other"],
    lumaQuestion: "Why are you not living in your own home?",
    required: false,
    skipIf: { field: "ownHomeNotLiving", equals: "No", goTo: 85 },
    tickPositions: { "Study":{x:180,y:693},"Medical treatment":{x:180,y:678},"Receiving care at someone's home":{x:180,y:662},"Receiving care in nursing home":{x:180,y:638},"Providing care":{x:180,y:618},"Overseas":{x:180,y:599},"Other":{x:180,y:583} } },

  { id: "soldFormerHome", questionNumber: 85, pageNumber: 18, x: 67, y: 453,
    fieldType: "select", label: "Sold Former Home", section: "income",
    pdfField: "Q85",
    options: ["Yes","No"],
    lumaQuestion: "Have you (or your partner) sold your former home within the last 2 years?",
    required: false,
    tickPositions: { "Yes":{x:67,y:453}, "No":{x:67,y:469} } },

  { id: "accommodationType", questionNumber: 86, pageNumber: 18, x: 501, y: 660,
    fieldType: "select", label: "Accommodation Type", section: "income",
    pdfField: "Q86",
    options: ["Own home","Renting privately","Public housing","Boarding house","Retirement village","Aged care home","Nursing home","Life interest","No rent (living rent free)","Other"],
    lumaQuestion: "What best describes where you currently live? 🏠",
    lumaExplanation: "This helps Centrelink determine if you qualify for Rent Assistance.",
    required: true,
    tickPositions: {
      "Own home":{x:501,y:660},"Renting privately":{x:501,y:720},"Public housing":{x:501,y:525},
      "Boarding house":{x:501,y:488},"Retirement village":{x:501,y:425},"Aged care home":{x:501,y:456},
      "Nursing home":{x:501,y:442},"Life interest":{x:501,y:397},"No rent (living rent free)":{x:501,y:379},"Other":{x:501,y:347}
    } },

  { id: "siteMooringFees", questionNumber: 87, pageNumber: 18, x: 351, y: 130,
    fieldType: "select", label: "Site or Mooring Fees", section: "income",
    pdfField: "Q87",
    options: ["Yes","No"],
    lumaQuestion: "Do you pay site or mooring fees for a caravan or boat?",
    required: false,
    skipIf: { field: "accommodationType", equals: "Own home", goTo: 88 },
    tickPositions: { "Yes":{x:351,y:114}, "No":{x:351,y:130} } },

  { id: "nameOnLease", questionNumber: 88, pageNumber: 18, x: 351, y: 205,
    fieldType: "select", label: "Name on Lease", section: "income",
    pdfField: "Q88",
    options: ["Yes","No"],
    lumaQuestion: "Is your name (or your partner's name) on the rental contract or lease?",
    required: false,
    skipIf: { field: "accommodationType", equals: "Own home", goTo: 89 },
    tickPositions: { "Yes":{x:351,y:190}, "No":{x:351,y:205} } },

  { id: "primaryTenantMarketRate", questionNumber: 89, pageNumber: 19, x: 84, y: 778,
    fieldType: "select", label: "Primary Tenant Market Rate", section: "income",
    pdfField: "Q89",
    options: ["Yes","No","Not sure"],
    lumaQuestion: "Is the primary tenant (the person on the lease) paying the market rate of rent?",
    required: false,
    skipIf: { field: "nameOnLease", equals: "Yes", goTo: 90 },
    tickPositions: { "Yes":{x:84,y:763},"No":{x:84,y:794},"Not sure":{x:84,y:778} } },

  { id: "liveWithPrimaryTenant", questionNumber: 90, pageNumber: 19, x: 67, y: 676,
    fieldType: "select", label: "Live With Primary Tenant", section: "income",
    pdfField: "Q90",
    options: ["Yes","No"],
    lumaQuestion: "Do you live with the primary tenant?",
    required: false,
    tickPositions: { "Yes":{x:67,y:676}, "No":{x:67,y:692} } },

  { id: "agedCareHomeName", questionNumber: 91, pageNumber: 19, x: 51, y: 577,
    fieldType: "text", label: "Aged Care Home Name", section: "income",
    pdfField: "Q91",
    lumaQuestion: "What is the name of the aged care home or nursing home you live in?",
    required: false, skipText: "none", maxWidth: 250,
    skipIf: { field: "accommodationType", equals: "Own home", goTo: 95 } },

  { id: "agedCareMoveInDate", questionNumber: 92, pageNumber: 19, x: 49, y: 508,
    fieldType: "date", label: "Aged Care Move In Date", section: "income",
    pdfFields: ["Q92.Y.D","Q92.Y.M","Q92.Y.Y"],
    lumaQuestion: "What date did you move into the aged care home? (DD/MM/YYYY)",
    required: false,
    dateBoxes: { ddX:49, ddY:508, mmX:84, mmY:508, yyyyX:118, yyyyY:508 },
    skipIf: { field: "accommodationType", equals: "Own home", goTo: 95 } },

  { id: "howLongStaying", questionNumber: 93, pageNumber: 19, x: 70, y: 408,
    fieldType: "select", label: "How Long Staying", section: "income",
    options: ["Long term or indefinitely","Short term or temporary respite care"],
    lumaQuestion: "How long will you be staying in the aged care home? Long term (permanent) or short term (respite/temporary)?",
    required: false,
    skipIf: { field: "accommodationType", equals: "Own home", goTo: 95 },
    tickPositions: { "Long term or indefinitely":{x:70,y:408},"Short term or temporary respite care":{x:70,y:371} } },

  { id: "giftLoanEntryFee", questionNumber: 96, pageNumber: 19, x: 350, y: 564,
    fieldType: "select", label: "Gift or Loan Entry Fee", section: "income",
    pdfField: "Q96",
    options: ["Yes","No"],
    lumaQuestion: "Did you (or your partner) make a gift or loan in addition to the entry contribution for your accommodation?",
    required: false,
    skipIf: { field: "accommodationType", equals: "Own home", goTo: 99 },
    tickPositions: { "Yes":{x:350,y:564}, "No":{x:350,y:580} } },

  { id: "giftLoanAmount", questionNumber: 97, pageNumber: 19, x: 344, y: 367,
    fieldType: "text", label: "Gift or Loan Amount", section: "income",
    pdfField: "Q97.Details.Gift",
    lumaQuestion: "What was the additional gift or loan amount? (e.g. '$50,000')",
    required: false, skipText: "none", maxWidth: 120,
    skipIf: { field: "giftLoanEntryFee", equals: "No", goTo: 99 } },

  { id: "paidEntryContribution", questionNumber: 99, pageNumber: 20, x: 70, y: 707,
    fieldType: "select", label: "Paid Entry Contribution", section: "income",
    pdfField: "Q99",
    options: ["Yes","No"],
    lumaQuestion: "Did you (or your partner) pay an entry contribution for your accommodation (e.g. aged care bond)?",
    required: false,
    skipIf: { field: "accommodationType", equals: "Own home", goTo: 100 },
    tickPositions: { "Yes":{x:70,y:707}, "No":{x:70,y:723} } },

  { id: "soldOrTransferredAssets", questionNumber: 102, pageNumber: 20, x: 70, y: 348,
    fieldType: "select", label: "Sold or Transferred Assets", section: "income",
    pdfField: "Q102",
    options: ["Yes","No"],
    lumaQuestion: "In the last 5 years, have you (or your partner) sold, gifted, or transferred any assets for less than their value? For example, a house, shares, or money given away. 💰",
    lumaExplanation: "This is called 'deprivation of assets'. Centrelink may still count these assets in your means test.",
    required: false,
    tickPositions: { "Yes":{x:70,y:348}, "No":{x:70,y:364} } },

  { id: "payBoardLodgings", questionNumber: 109, pageNumber: 21, x: 350, y: 707,
    fieldType: "select", label: "Pay Board or Lodgings", section: "income",
    pdfField: "Q109",
    options: ["Yes","No"],
    lumaQuestion: "Do you pay board and/or lodgings?",
    required: false,
    skipIf: { field: "accommodationType", equals: "Own home", goTo: 113 },
    tickPositions: { "Yes":{x:350,y:692}, "No":{x:350,y:707} } },

  { id: "boardLodgingsAmount", questionNumber: 111, pageNumber: 21, x: 381, y: 602,
    fieldType: "text", label: "Board/Lodgings Amount", section: "income",
    pdfField: "Q111.Paid",
    lumaQuestion: "How much do you pay per week for board and/or lodgings? (e.g. '250')",
    required: false, skipText: "none", maxWidth: 100,
    skipIf: { field: "payBoardLodgings", equals: "No", goTo: 113 } },

  { id: "totalAmountCharged", questionNumber: 114, pageNumber: 22, x: 348, y: 480,
    fieldType: "text", label: "Total Amount Charged", section: "income",
    pdfField: "Q114.Paid",
    lumaQuestion: "What is the total amount you are charged per week for your accommodation (including board, meals, and lodgings)?",
    required: false, skipText: "none", maxWidth: 100,
    skipIf: { field: "payBoardLodgings", equals: "No", goTo: 115 } },

  { id: "formalLease", questionNumber: 115, pageNumber: 22, x: 70, y: 565,
    fieldType: "select", label: "Formal Lease", section: "income",
    pdfField: "Q115",
    options: ["Yes","No"],
    lumaQuestion: "Do you have a formal lease or tenancy agreement?",
    required: false,
    skipIf: { field: "accommodationType", equals: "Own home", goTo: 116 },
    tickPositions: { "Yes":{x:70,y:565}, "No":{x:70,y:581} } },

  { id: "stoppedWorkingLastYear", questionNumber: 116, pageNumber: 22, x: 67, y: 711,
    fieldType: "select", label: "Stopped Working Last Year", section: "income",
    pdfField: "Q116",
    options: ["Yes","No"],
    lumaQuestion: "In the last 12 months, did you (or your partner) stop working for any employer or stop self-employment? 📋",
    required: false,
    tickPositions: { "Yes":{x:67,y:696}, "No":{x:67,y:711} } },

  { id: "employerLastYear", questionNumber: 116, pageNumber: 22, x: 339, y: 355,
    fieldType: "text", label: "Employer or Business Name", section: "income",
    pdfField: "116.Name.0",
    lumaQuestion: "What was the name of your employer or business?",
    required: false, skipText: "none", maxWidth: 250,
    skipIf: { field: "stoppedWorkingLastYear", equals: "No", goTo: 117 } },

  { id: "leaveEntitlementPayment", questionNumber: 117, pageNumber: 22, x: 350, y: 660,
    fieldType: "select", label: "Leave Entitlement Payment", section: "income",
    pdfField: "Q117",
    options: ["Yes","No"],
    lumaQuestion: "In the last 12 months, did you (or your partner) get any leave entitlement payments? This includes annual leave, long service leave, maternity leave, or leave cashed in when you stopped work.",
    required: false,
    tickPositions: { "Yes":{x:350,y:644}, "No":{x:350,y:660} } },

  { id: "redundancyPayment", questionNumber: 118, pageNumber: 23, x: 70, y: 581,
    fieldType: "select", label: "Redundancy Payment", section: "income",
    pdfField: "Q118",
    options: ["Yes","No"],
    lumaQuestion: "Did you (or your partner) receive a redundancy, severance, or invalidity payment in the last 2 years?",
    required: false,
    tickPositions: { "Yes":{x:70,y:565}, "No":{x:70,y:581} } },

  { id: "hasTFN", questionNumber: 120, pageNumber: 23, x: 372, y: 619,
    fieldType: "select", label: "Has Tax File Number", section: "income",
    pdfField: "Q120Y",
    options: ["Yes","No"],
    lumaQuestion: "Do you have a Tax File Number (TFN)? 🔢",
    lumaExplanation: "Your TFN is a 9-digit number from the ATO. You can find it on your tax return or myGov.",
    required: true,
    tickPositions: { "Yes":{x:372,y:619}, "No":{x:372,y:635} } },

  { id: "tfnNumber", questionNumber: 120, pageNumber: 23, x: 372, y: 515,
    fieldType: "text", label: "Tax File Number", section: "income",
    pdfField: "Q120YDetails.0",
    lumaQuestion: "What is your Tax File Number? (9 digits)",
    required: false, skipText: "none", maxWidth: 120,
    skipIf: { field: "hasTFN", equals: "No", goTo: 121 } },

  { id: "youngerThan21", questionNumber: 121, pageNumber: 23, x: 70, y: 416,
    fieldType: "select", label: "Younger Than 21", section: "income",
    pdfField: "Q121",
    options: ["Yes","No"],
    lumaQuestion: "Are you younger than 21 years old?",
    required: true,
    tickPositions: { "Yes":{x:70,y:416}, "No":{x:70,y:432} } },

  { id: "liveWithParents", questionNumber: 124, pageNumber: 25, x: 70, y: 792,
    fieldType: "select", label: "Live With Parents", section: "income",
    pdfField: "Q124",
    options: ["Yes","No"],
    lumaQuestion: "Do you currently live with your parent(s)?",
    required: false,
    skipIf: { field: "youngerThan21", equals: "No", goTo: 128 },
    tickPositions: { "Yes":{x:70,y:776}, "No":{x:70,y:792} } },

  { id: "youngerThan18", questionNumber: 125, pageNumber: 25, x: 70, y: 719,
    fieldType: "select", label: "Younger Than 18", section: "income",
    pdfField: "Q125",
    options: ["Yes","No"],
    lumaQuestion: "Are you younger than 18 years old?",
    required: false,
    skipIf: { field: "youngerThan21", equals: "No", goTo: 128 },
    tickPositions: { "Yes":{x:70,y:689}, "No":{x:70,y:719} } },

  { id: "liveAwayFromParents", questionNumber: 126, pageNumber: 25, x: 70, y: 615,
    fieldType: "select", label: "Live Away From Parents", section: "income",
    pdfField: "Q126",
    options: ["Yes","No"],
    lumaQuestion: "Do you live away from your parents' home because of a medical condition or disability?",
    required: false,
    skipIf: { field: "youngerThan21", equals: "No", goTo: 128 },
    tickPositions: { "Yes":{x:70,y:615}, "No":{x:70,y:631} } },

  { id: "unreasonableToLiveAtHome", questionNumber: 127, pageNumber: 25, x: 70, y: 486,
    fieldType: "select", label: "Unreasonable to Live at Home", section: "income",
    pdfField: "Q127",
    options: ["Yes","No"],
    lumaQuestion: "Is it unreasonable for you to live at home with your parents? For example, due to family breakdown or violence.",
    required: false,
    skipIf: { field: "youngerThan21", equals: "No", goTo: 128 },
    tickPositions: { "Yes":{x:70,y:453}, "No":{x:70,y:486} },
    conditionalNotice: {
      whenAnswer: "Yes",
      notice: "📞 Action needed: Since it's unreasonable for you to live at home, you'll need to make an appointment with a Centrelink Social Worker to discuss your situation.\n\nCall Centrelink on 132 717 to arrange this appointment.\n\nI'll add this to your checklist at the end."
    } },

  // ═══════════════════════════════════════════════════════════════
  // PART D — DISABILITY AND MEDICAL CONDITION (Q131-Q142)
  // ═══════════════════════════════════════════════════════════════

  { id: "primaryCondition", questionNumber: 131, pageNumber: 29, x: 54, y: 400,
    fieldType: "text", label: "Primary Medical Condition", section: "disability",
    pdfField: "Q131",
    lumaQuestion: "What is your main medical condition, disability, or injury? This is the condition that most affects your ability to work — describe it in your own words. 🏥",
    required: true, maxWidth: 450 },

  { id: "conditionStartDate", questionNumber: 132, pageNumber: 29, x: 52, y: 49,
    fieldType: "text", label: "When Condition Started", section: "disability",
    pdfFields: ["Q132.M","Q132.Y"],
    lumaQuestion: "When did this condition first significantly affect your ability to work? An approximate date is fine — for example 'March 2019' or 'about 5 years ago'. 📅",
    required: false, skipText: "unknown", maxWidth: 200 },

  { id: "conditionCategory", questionNumber: 133, pageNumber: 29, x: 67, y: 763,
    fieldType: "select", label: "Condition Category", section: "disability",
    pdfField: "Q133",
    options: ["Permanently blind","Need nursing home level care","Terminal illness (less than 2 years)","Intellectual disability (IQ under 70)","Category 4 HIV/AIDS","None of these"],
    lumaQuestion: "Which of these best describes your condition? A: Permanently blind  B: Need nursing home level care  C: Terminal illness (life expectancy under 2 years)  D: Intellectual disability (IQ under 70)  E: Category 4 HIV/AIDS  Or say 'none of these'.",
    required: true },

  { id: "currentTreatment", questionNumber: 135, pageNumber: 31, x: 335, y: 462,
    fieldType: "text", label: "Current Treatment", section: "disability",
    pdfField: "Q135.CT",
    lumaQuestion: "What treatment are you currently receiving for your condition? Include medications, therapy, and appointments. Write 'none' if you are not currently receiving any treatment. 💊",
    lumaExplanation: "Centrelink needs to know your condition is being reasonably treated.",
    required: true, maxWidth: 400 },

  { id: "pastTreatment", questionNumber: 135, pageNumber: 31, x: 54, y: 350,
    fieldType: "text", label: "Past Treatment", section: "disability",
    pdfField: "Q135.PT",
    lumaQuestion: "What treatments have you had in the past for your condition? Say 'none' if not applicable.",
    required: false, skipText: "none", maxWidth: 400 },

  { id: "futureTreatment", questionNumber: 135, pageNumber: 31, x: 335, y: 94,
    fieldType: "text", label: "Future Treatment", section: "disability",
    pdfField: "Q135.FT",
    lumaQuestion: "What future treatment is planned for your condition? Say 'none' if not applicable.",
    required: false, skipText: "none", maxWidth: 400 },

  { id: "attendedSpecialSchool", questionNumber: 136, pageNumber: 32, x: 70, y: 740,
    fieldType: "select", label: "Attended Special School", section: "disability",
    pdfField: "Q136",
    options: ["Yes","No"],
    lumaQuestion: "Have you ever attended a special school or Special Education Unit because of your condition? (Even if many years ago) 🏫",
    required: false,
    tickPositions: { "Yes":{x:70,y:724}, "No":{x:70,y:740} } },

  { id: "previousWorkType", questionNumber: 137, pageNumber: 32, x: 58, y: 524,
    fieldType: "text", label: "Previous Work Type", section: "disability",
    pdfField: "Q137.D0.WorkType",
    lumaQuestion: "What type of work have you done in the last 12 months? For example: office work, labouring, retail, driving. Say 'none' if you didn't work. 💼",
    required: false, skipText: "none", maxWidth: 250 },

  { id: "workAffectedByCondition", questionNumber: 137, pageNumber: 32, x: 74, y: 479,
    fieldType: "select", label: "Work Affected by Condition", section: "disability",
    pdfField: "Q137.D0.AffectWork",
    options: ["Yes","No"],
    lumaQuestion: "Did your condition affect your ability to do that work?",
    required: false,
    skipIf: { field: "previousWorkType", equals: "none", goTo: 138 },
    tickPositions: { "Yes":{x:74,y:479}, "No":{x:74,y:495} } },

  { id: "workplaceSupport", questionNumber: 138, pageNumber: 32, x: 557, y: 724,
    fieldType: "select", label: "Workplace Support", section: "disability",
    options: ["Modified environment","Reduced hours","Alternative duties","Retraining","On-the-job support","None"],
    lumaQuestion: "Did you (or do you) get any extra support at work because of your condition? For example: reduced hours, alternative duties, modified environment, on-the-job support. Say 'none' if not.",
    required: false },

  { id: "programOfSupport", questionNumber: 139, pageNumber: 32, x: 67, y: 724,
    fieldType: "select", label: "Program of Support", section: "disability",
    pdfField: "Q139",
    options: ["Yes","No"],
    lumaQuestion: "Have you participated in a Program of Support (like Workforce Australia or a job preparation program) in the last 3 years? 📋",
    lumaExplanation: "Most DSP claimants need to have participated in a Program of Support within the last 3 years.",
    required: true,
    tickPositions: { "Yes":{x:67,y:724}, "No":{x:67,y:740} } },

  { id: "treatingDoctor", questionNumber: 140, pageNumber: 33, x: 57, y: 701,
    fieldType: "text", label: "Treating Doctor Name", section: "disability",
    pdfField: "Q140.D0.FullName",
    lumaQuestion: "What is the full name of your main treating doctor or health professional? 👨‍⚕️",
    required: true, maxWidth: 220 },

  { id: "doctorProfession", questionNumber: 140, pageNumber: 33, x: 57, y: 667,
    fieldType: "text", label: "Doctor Profession", section: "disability",
    pdfField: "Q140.D0.Profession",
    lumaQuestion: "What type of doctor or health professional is this? For example: GP, Psychiatrist, Physiotherapist, Neurologist.",
    required: false, skipText: "GP", maxWidth: 220 },

  { id: "doctorAddress", questionNumber: 140, pageNumber: 33, x: 56, y: 633,
    fieldType: "text", label: "Doctor Address", section: "disability",
    pdfFields: ["Q140.D0.Address1","Q140.D0.Address2","Q140.D0.Postcode"],
    lumaQuestion: "What is the address of your doctor's clinic?",
    required: false, skipText: "none", maxWidth: 220 },

  { id: "doctorPhone", questionNumber: 140, pageNumber: 33, x: 54, y: 558,
    fieldType: "text", label: "Doctor Phone", section: "disability",
    pdfField: "Q140.D0.PhoneNo",
    lumaQuestion: "What is your doctor's phone number? Say 'none' if you don't know.",
    required: false, skipText: "none", maxWidth: 150 },

  { id: "doctor2Name", questionNumber: 140, pageNumber: 33, x: 57, y: 511,
    fieldType: "text", label: "Second Doctor Name", section: "disability",
    pdfField: "Q140.D1.FullName",
    lumaQuestion: "Do you have a second treating doctor or specialist? If so, what is their name? Say 'none' if not.",
    required: false, skipText: "none", maxWidth: 220,
    skipIfValues: ["none","no","n/a"] },

  { id: "doctor2Profession", questionNumber: 140, pageNumber: 33, x: 57, y: 477,
    fieldType: "text", label: "Second Doctor Profession", section: "disability",
    pdfField: "Q140.D1.Profession",
    lumaQuestion: "What type of specialist is your second doctor?",
    required: false, skipText: "none", maxWidth: 220,
    skipIf: { field: "doctor2Name", equals: "none", goTo: 141 } },

  { id: "doctor2Address", questionNumber: 140, pageNumber: 33, x: 56, y: 443,
    fieldType: "text", label: "Second Doctor Address", section: "disability",
    pdfFields: ["Q140.D1.Address1","Q140.D1.Address2","Q140.D1.Postcode"],
    lumaQuestion: "What is the address of your second doctor's clinic?",
    required: false, skipText: "none", maxWidth: 220,
    skipIf: { field: "doctor2Name", equals: "none", goTo: 141 } },

  { id: "doctor2Phone", questionNumber: 140, pageNumber: 33, x: 54, y: 368,
    fieldType: "text", label: "Second Doctor Phone", section: "disability",
    pdfField: "Q140.D1.PhoneNo",
    lumaQuestion: "What is the phone number for your second doctor?",
    required: false, skipText: "none",
    skipIf: { field: "doctor2Name", equals: "none", goTo: 141 } },

  { id: "doctor3Name", questionNumber: 140, pageNumber: 33, x: 57, y: 321,
    fieldType: "text", label: "Third Doctor Name", section: "disability",
    pdfField: "Q140.D2.FullName",
    lumaQuestion: "Do you have a third treating doctor or specialist? If so, what is their name? Say 'none' if not.",
    required: false, skipText: "none", maxWidth: 220,
    skipIf: { field: "doctor2Name", equals: "none", goTo: 141 },
    skipIfValues: ["none","no","n/a"] },

  { id: "doctor3Profession", questionNumber: 140, pageNumber: 33, x: 57, y: 287,
    fieldType: "text", label: "Third Doctor Profession", section: "disability",
    pdfField: "Q140.D2.Profession",
    lumaQuestion: "What type of specialist is your third doctor?",
    required: false, skipText: "none",
    skipIf: { field: "doctor3Name", equals: "none", goTo: 141 } },

  { id: "doctor3Address", questionNumber: 140, pageNumber: 33, x: 56, y: 252,
    fieldType: "text", label: "Third Doctor Address", section: "disability",
    pdfFields: ["Q140.D2.Address1","Q140.D2.Address2","Q140.D2.Postcode"],
    lumaQuestion: "What is the address for your third doctor?",
    required: false, skipText: "none",
    skipIf: { field: "doctor3Name", equals: "none", goTo: 141 } },

  { id: "doctor3Phone", questionNumber: 140, pageNumber: 33, x: 54, y: 177,
    fieldType: "text", label: "Third Doctor Phone", section: "disability",
    pdfField: "Q140.D2.PhoneNo",
    lumaQuestion: "What is the phone number for your third doctor?",
    required: false, skipText: "none",
    skipIf: { field: "doctor3Name", equals: "none", goTo: 141 } },

  { id: "difficultyEvidence", questionNumber: 142, pageNumber: 34, x: 70, y: 792,
    fieldType: "select", label: "Difficulty Getting Evidence", section: "disability",
    pdfField: "Q142",
    options: ["Yes","No"],
    lumaQuestion: "Are you having difficulty getting the medical evidence Centrelink needs? If yes, Centrelink can help. 📋",
    required: false,
    tickPositions: { "Yes":{x:70,y:777}, "No":{x:70,y:792} } },

  // ═══════════════════════════════════════════════════════════════
  // DECLARATION
  // ═══════════════════════════════════════════════════════════════

  { id: "declarationComplete", questionNumber: 144, pageNumber: 36, x: 0, y: 0,
    fieldType: "select", label: "Declaration", section: "declaration",
    options: ["Yes"],
    lumaQuestion: "",
    required: false,
    signatureNotice: "You've answered all the questions! ✅ Before we finish, you need to sign the declaration on page 36 to confirm the information is correct. Please add your signature in the panel on the right, then click Download." },
];
