/**
 * SA466 Disability Support Pension Claim — Complete Field Map
 *
 * Every field the form asks for, with:
 *   - questionNumber: order Luma follows
 *   - pageNumber: 0-based PDF page
 *   - x, y: PDF coordinates (origin bottom-left, A4 595×842pt)
 *   - fieldType: "text" | "tick" | "date" | "select"
 *   - lumaQuestion: plain-language question Luma asks
 *   - lumaExplanation?: optional explainer before the question
 *   - options?: for select / tick fields
 *   - required: whether the field must be answered
 *   - skipIf?: { field: string; equals: string; goTo: number } — skip logic
 *   - signatureNotice?: string — tells user to sign by hand
 *   - skipText?: hint for optional fields
 *   - maxWidth?: for long text wrapping
 */

export interface SA466Field {
  id: string;
  questionNumber: number;
  pageNumber: number;
  x: number;
  y: number;
  fieldType: "text" | "tick" | "date" | "select";
  lumaQuestion: string;
  lumaExplanation?: string;
  options?: string[];
  required: boolean;
  skipIf?: { field: string; equals: string; goTo: number };
  signatureNotice?: string;
  skipText?: string;
  maxWidth?: number;
  // For date fields: individual box positions for DD, MM, YYYY
  dateBoxes?: { ddX: number; ddY: number; mmX: number; mmY: number; yyyyX: number; yyyyY: number };
  // For tick fields: positions for each option value
  tickPositions?: Record<string, { x: number; y: number }>;
  label: string;
  section: string;
}

export const SA466_SECTIONS = [
  { id: "personal", title: "Part A — Your Personal Details", startQ: 1, endQ: 14 },
  { id: "residence", title: "Part B — Your Residence", startQ: 15, endQ: 22 },
  { id: "payment", title: "Part C — Payment Details", startQ: 23, endQ: 27 },
  { id: "disability", title: "Part D — Your Disability or Medical Condition", startQ: 28, endQ: 38 },
  { id: "work", title: "Part E — Your Work History", startQ: 39, endQ: 45 },
  { id: "income", title: "Part F — Income and Assets", startQ: 46, endQ: 56 },
  { id: "partner", title: "Part G — Your Partner", startQ: 57, endQ: 64 },
  { id: "bank", title: "Part H — Bank Account Details", startQ: 65, endQ: 69 },
  { id: "declaration", title: "Part I — Declaration", startQ: 70, endQ: 72 },
] as const;

export const SA466_FIELDS: SA466Field[] = [
  // ────────────────────────────────────────────
  // PART A — PERSONAL DETAILS (pages 1-3)
  // ────────────────────────────────────────────
  // ── PAGE 7 (pageNumber: 6) — Personal Details ──
  // y values are TOP offsets: actual PDF y = pageHeight - y
  {
    id: "title",
    questionNumber: 1,
    pageNumber: 6,
    x: 147, y: 175,
    fieldType: "select",
    label: "Title",
    section: "personal",
    options: ["Mr", "Mrs", "Ms", "Miss", "Dr"],
    lumaQuestion: "First up — how would you like to be addressed? 😊",
    required: true,
    tickPositions: {
      "Mr": { x: 147, y: 175 },
      "Mrs": { x: 177, y: 175 },
      "Ms": { x: 207, y: 175 },
      "Miss": { x: 237, y: 175 },
      "Dr": { x: 267, y: 175 },
    },
  },
  {
    id: "familyName",
    questionNumber: 2,
    pageNumber: 6,
    x: 162, y: 632,
    fieldType: "text",
    label: "Family Name",
    section: "personal",
    lumaQuestion: "What is your family name (surname)?",
    required: true,
    maxWidth: 200,
  },
  {
    id: "firstName",
    questionNumber: 3,
    pageNumber: 6,
    x: 162, y: 608,
    fieldType: "text",
    label: "First Name",
    section: "personal",
    lumaQuestion: "And your first (given) name?",
    required: true,
    maxWidth: 200,
  },
  {
    id: "secondName",
    questionNumber: 4,
    pageNumber: 6,
    x: 147, y: 244,
    fieldType: "text",
    label: "Second/Middle Name",
    section: "personal",
    lumaQuestion: "Do you have a middle or second name? If not, just say \"none\" 😊",
    required: false,
    skipText: "none",
    maxWidth: 200,
  },
  {
    id: "otherNames",
    questionNumber: 5,
    pageNumber: 6,
    x: 147, y: 270,
    fieldType: "text",
    label: "Other Names Used",
    section: "personal",
    lumaQuestion: "Have you ever used a different name? For example, your name before marriage, or a nickname on official documents?",
    lumaExplanation: "The government needs this to check their records under any name you may have used before.",
    required: false,
    skipText: "none",
    maxWidth: 200,
  },
  {
    id: "dob",
    questionNumber: 6,
    pageNumber: 6,
    x: 162, y: 560,
    fieldType: "date",
    label: "Date of Birth",
    section: "personal",
    lumaQuestion: "What is your date of birth? You can type it as DD/MM/YYYY 📅",
    required: true,
    dateBoxes: { ddX: 162, ddY: 560, mmX: 196, mmY: 560, yyyyX: 230, yyyyY: 560 },
  },
  {
    id: "gender",
    questionNumber: 7,
    pageNumber: 6,
    x: 147, y: 296,
    fieldType: "select",
    label: "Gender",
    section: "personal",
    options: ["Male", "Female", "Other"],
    lumaQuestion: "What is your gender?",
    lumaExplanation: "This is for the government's records only — choose whichever feels right for you.",
    required: true,
    tickPositions: {
      "Male": { x: 147, y: 296 },
      "Female": { x: 197, y: 296 },
      "Other": { x: 247, y: 296 },
    },
  },
  {
    id: "permanentAddress",
    questionNumber: 8,
    pageNumber: 6,
    x: 147, y: 322,
    fieldType: "text",
    label: "Home Address",
    section: "personal",
    lumaQuestion: "What is your home address? Include street number, street name, suburb, and state 🏠",
    lumaExplanation: "This is the address where you actually live — not a PO Box.",
    required: true,
    maxWidth: 300,
  },
  {
    id: "postcode",
    questionNumber: 9,
    pageNumber: 6,
    x: 430, y: 322,
    fieldType: "text",
    label: "Postcode",
    section: "personal",
    lumaQuestion: "And your postcode?",
    required: true,
  },
  {
    id: "postalAddressSame",
    questionNumber: 10,
    pageNumber: 6,
    x: 147, y: 370,
    fieldType: "select",
    label: "Postal Address Same?",
    section: "personal",
    options: ["Yes", "No"],
    lumaQuestion: "Is your postal address the same as your home address?",
    lumaExplanation: "Your postal address is where you want to receive letters from the government.",
    required: true,
    tickPositions: {
      "Yes": { x: 147, y: 370 },
      "No": { x: 197, y: 370 },
    },
  },
  {
    id: "postalAddress",
    questionNumber: 11,
    pageNumber: 6,
    x: 147, y: 396,
    fieldType: "text",
    label: "Postal Address",
    section: "personal",
    lumaQuestion: "What is your postal address?",
    required: true,
    skipIf: { field: "postalAddressSame", equals: "Yes", goTo: 12 },
    maxWidth: 300,
  },

  // ── PAGE 8 (pageNumber: 7) — Contact Details ──
  {
    id: "homePhone",
    questionNumber: 12,
    pageNumber: 7,
    x: 370, y: 620,
    fieldType: "text",
    label: "Home Phone",
    section: "personal",
    lumaQuestion: "Do you have a home phone number? If not, just say \"none\" 📞",
    required: false,
    skipText: "none",
  },
  {
    id: "mobile",
    questionNumber: 13,
    pageNumber: 7,
    x: 370, y: 600,
    fieldType: "text",
    label: "Mobile Number",
    section: "personal",
    lumaQuestion: "What is your mobile phone number? 📱",
    required: true,
  },
  {
    id: "email",
    questionNumber: 14,
    pageNumber: 7,
    x: 200, y: 582,
    fieldType: "text",
    label: "Email Address",
    section: "personal",
    lumaQuestion: "What is your email address? If you don't have one, just say \"none\" ✉️",
    required: false,
    skipText: "none",
    maxWidth: 250,
  },

  // ────────────────────────────────────────────
  // PART B — RESIDENCE (pages 3-5)
  // ────────────────────────────────────────────
  {
    id: "crn",
    questionNumber: 15,
    pageNumber: 2,
    x: 130, y: 710,
    fieldType: "text",
    label: "Customer Reference Number",
    section: "residence",
    lumaQuestion: "Do you have a Centrelink Customer Reference Number (CRN)?",
    lumaExplanation: "This is a 9-digit number on your Centrelink card. If you have never had a Centrelink card or don't know your number, just say \"none\" — that is perfectly fine!",
    required: false,
    skipText: "none",
  },
  {
    id: "australianCitizen",
    questionNumber: 16,
    pageNumber: 2,
    x: 130, y: 680,
    fieldType: "select",
    label: "Australian Citizen",
    section: "residence",
    options: ["Yes", "No"],
    lumaQuestion: "Are you an Australian citizen?",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 680 },
      "No": { x: 180, y: 680 },
    },
  },
  {
    id: "permanentResident",
    questionNumber: 17,
    pageNumber: 2,
    x: 130, y: 655,
    fieldType: "select",
    label: "Permanent Resident",
    section: "residence",
    options: ["Yes", "No"],
    lumaQuestion: "Are you a permanent resident of Australia?",
    lumaExplanation: "A permanent resident has a visa that lets them live in Australia permanently.",
    required: true,
    skipIf: { field: "australianCitizen", equals: "Yes", goTo: 19 },
    tickPositions: {
      "Yes": { x: 130, y: 655 },
      "No": { x: 180, y: 655 },
    },
  },
  {
    id: "visaType",
    questionNumber: 18,
    pageNumber: 2,
    x: 130, y: 630,
    fieldType: "text",
    label: "Visa Type/Number",
    section: "residence",
    lumaQuestion: "What type of visa do you have? If you know the visa number, please include it.",
    required: false,
    skipIf: { field: "australianCitizen", equals: "Yes", goTo: 19 },
    skipText: "don't know",
  },
  {
    id: "arrivalDate",
    questionNumber: 19,
    pageNumber: 2,
    x: 130, y: 600,
    fieldType: "date",
    label: "Date of Arrival in Australia",
    section: "residence",
    lumaQuestion: "When did you first arrive in Australia? Type the date as DD/MM/YYYY. If you were born here, say \"born here\".",
    required: false,
    skipText: "born here",
    dateBoxes: { ddX: 130, ddY: 600, mmX: 165, mmY: 600, yyyyX: 200, yyyyY: 600 },
  },
  {
    id: "countryOfBirth",
    questionNumber: 20,
    pageNumber: 2,
    x: 130, y: 570,
    fieldType: "text",
    label: "Country of Birth",
    section: "residence",
    lumaQuestion: "What country were you born in?",
    required: true,
  },
  {
    id: "travelledOverseas",
    questionNumber: 21,
    pageNumber: 3,
    x: 130, y: 710,
    fieldType: "select",
    label: "Travelled Overseas",
    section: "residence",
    options: ["Yes", "No"],
    lumaQuestion: "Have you travelled outside Australia in the last 12 months?",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 710 },
      "No": { x: 180, y: 710 },
    },
  },
  {
    id: "travelDates",
    questionNumber: 22,
    pageNumber: 3,
    x: 130, y: 685,
    fieldType: "text",
    label: "Travel Dates",
    section: "residence",
    lumaQuestion: "What dates were you overseas? Please tell me the dates you left and returned.",
    required: true,
    skipIf: { field: "travelledOverseas", equals: "No", goTo: 23 },
    maxWidth: 350,
  },

  // ────────────────────────────────────────────
  // PART C — PAYMENT DETAILS (pages 5-6)
  // ────────────────────────────────────────────
  {
    id: "taxFileNumber",
    questionNumber: 23,
    pageNumber: 4,
    x: 130, y: 710,
    fieldType: "text",
    label: "Tax File Number",
    section: "payment",
    lumaQuestion: "What is your Tax File Number (TFN)?",
    lumaExplanation: "Your TFN is a 9-digit number from the tax office. If you don't have one or don't know it, say \"none\" — Centrelink can look it up.",
    required: false,
    skipText: "none",
  },
  {
    id: "receivingPayment",
    questionNumber: 24,
    pageNumber: 4,
    x: 130, y: 680,
    fieldType: "select",
    label: "Currently Receiving Payment",
    section: "payment",
    options: ["Yes", "No"],
    lumaQuestion: "Are you currently receiving any payments from Centrelink?",
    lumaExplanation: "This includes JobSeeker, Youth Allowance, Carer Payment, or any other government payment.",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 680 },
      "No": { x: 180, y: 680 },
    },
  },
  {
    id: "currentPaymentType",
    questionNumber: 25,
    pageNumber: 4,
    x: 130, y: 655,
    fieldType: "text",
    label: "Current Payment Type",
    section: "payment",
    lumaQuestion: "What payment are you currently receiving?",
    required: true,
    skipIf: { field: "receivingPayment", equals: "No", goTo: 26 },
  },
  {
    id: "claimStartDate",
    questionNumber: 26,
    pageNumber: 4,
    x: 130, y: 625,
    fieldType: "date",
    label: "Claim Start Date",
    section: "payment",
    lumaQuestion: "From what date do you want this Disability Support Pension to start? If you want it to start from today, say \"today\".",
    lumaExplanation: "Usually this is today's date or the date you became unable to work due to your condition.",
    required: true,
    dateBoxes: { ddX: 130, ddY: 625, mmX: 165, mmY: 625, yyyyX: 200, yyyyY: 625 },
  },
  {
    id: "interpreterNeeded",
    questionNumber: 27,
    pageNumber: 4,
    x: 130, y: 595,
    fieldType: "select",
    label: "Interpreter Needed",
    section: "payment",
    options: ["Yes", "No"],
    lumaQuestion: "Do you need an interpreter when dealing with Centrelink?",
    lumaExplanation: "If you are more comfortable speaking in a language other than English, Centrelink can arrange a free interpreter for you.",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 595 },
      "No": { x: 180, y: 595 },
    },
  },

  // ────────────────────────────────────────────
  // PART D — DISABILITY / MEDICAL CONDITION (pages 6-10)
  // ────────────────────────────────────────────
  {
    id: "primaryCondition",
    questionNumber: 28,
    pageNumber: 5,
    x: 130, y: 710,
    fieldType: "text",
    label: "Primary Medical Condition",
    section: "disability",
    lumaQuestion: "What is your main medical condition, disability, or injury?",
    lumaExplanation: "This is the condition that most affects your ability to work. Just describe it in your own words — for example, 'back injury' or 'depression and anxiety'.",
    required: true,
    maxWidth: 350,
  },
  {
    id: "conditionStartDate",
    questionNumber: 29,
    pageNumber: 5,
    x: 130, y: 680,
    fieldType: "date",
    label: "Condition Start Date",
    section: "disability",
    lumaQuestion: "When did this condition first start? An approximate date is fine — for example, \"March 2019\" or \"about 5 years ago\".",
    required: true,
    dateBoxes: { ddX: 130, ddY: 680, mmX: 165, mmY: 680, yyyyX: 200, yyyyY: 680 },
  },
  {
    id: "otherConditions",
    questionNumber: 30,
    pageNumber: 5,
    x: 130, y: 650,
    fieldType: "text",
    label: "Other Medical Conditions",
    section: "disability",
    lumaQuestion: "Do you have any other medical conditions, disabilities, or injuries? If not, say \"none\".",
    required: false,
    skipText: "none",
    maxWidth: 350,
  },
  {
    id: "treatingDoctor",
    questionNumber: 31,
    pageNumber: 5,
    x: 130, y: 610,
    fieldType: "text",
    label: "Treating Doctor's Name",
    section: "disability",
    lumaQuestion: "What is the name of your main doctor who treats your condition?",
    required: true,
    maxWidth: 250,
  },
  {
    id: "doctorAddress",
    questionNumber: 32,
    pageNumber: 5,
    x: 130, y: 585,
    fieldType: "text",
    label: "Doctor's Address",
    section: "disability",
    lumaQuestion: "What is the address or clinic name of your doctor?",
    required: true,
    maxWidth: 350,
  },
  {
    id: "doctorPhone",
    questionNumber: 33,
    pageNumber: 5,
    x: 130, y: 560,
    fieldType: "text",
    label: "Doctor's Phone",
    section: "disability",
    lumaQuestion: "What is your doctor's phone number?",
    required: false,
    skipText: "don't know",
  },
  {
    id: "hospitalised",
    questionNumber: 34,
    pageNumber: 6,
    x: 130, y: 710,
    fieldType: "select",
    label: "Hospitalised Recently",
    section: "disability",
    options: ["Yes", "No"],
    lumaQuestion: "Have you been in hospital because of your condition in the last 12 months?",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 710 },
      "No": { x: 180, y: 710 },
    },
  },
  {
    id: "hospitalDetails",
    questionNumber: 35,
    pageNumber: 6,
    x: 130, y: 685,
    fieldType: "text",
    label: "Hospital Details",
    section: "disability",
    lumaQuestion: "Which hospital were you in and when?",
    required: true,
    skipIf: { field: "hospitalised", equals: "No", goTo: 36 },
    maxWidth: 350,
  },
  {
    id: "medication",
    questionNumber: 36,
    pageNumber: 6,
    x: 130, y: 650,
    fieldType: "text",
    label: "Current Medications",
    section: "disability",
    lumaQuestion: "What medications are you currently taking? If none, say \"none\".",
    lumaExplanation: "List all medicines you take regularly, including any over-the-counter or herbal medicines.",
    required: false,
    skipText: "none",
    maxWidth: 350,
  },
  {
    id: "mobilityAids",
    questionNumber: 37,
    pageNumber: 6,
    x: 130, y: 610,
    fieldType: "text",
    label: "Mobility Aids",
    section: "disability",
    lumaQuestion: "Do you use any aids or equipment because of your condition? For example, a wheelchair, walking stick, hearing aid. If none, say \"none\".",
    required: false,
    skipText: "none",
    maxWidth: 350,
  },
  {
    id: "conditionPermanent",
    questionNumber: 38,
    pageNumber: 6,
    x: 130, y: 575,
    fieldType: "select",
    label: "Condition Permanent",
    section: "disability",
    options: ["Yes", "No", "Not sure"],
    lumaQuestion: "Is your condition likely to be permanent? That means it will probably not get better even with treatment.",
    lumaExplanation: "It is okay to say 'not sure' — your doctor's report will help Centrelink decide this.",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 575 },
      "No": { x: 180, y: 575 },
      "Not sure": { x: 230, y: 575 },
    },
  },

  // ────────────────────────────────────────────
  // PART E — WORK HISTORY (pages 10-12)
  // ────────────────────────────────────────────
  {
    id: "currentlyWorking",
    questionNumber: 39,
    pageNumber: 8,
    x: 130, y: 710,
    fieldType: "select",
    label: "Currently Working",
    section: "work",
    options: ["Yes", "No"],
    lumaQuestion: "Are you currently working at all — even a few hours a week?",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 710 },
      "No": { x: 180, y: 710 },
    },
  },
  {
    id: "employerName",
    questionNumber: 40,
    pageNumber: 8,
    x: 130, y: 685,
    fieldType: "text",
    label: "Employer Name",
    section: "work",
    lumaQuestion: "What is the name of your employer?",
    required: true,
    skipIf: { field: "currentlyWorking", equals: "No", goTo: 43 },
    maxWidth: 250,
  },
  {
    id: "hoursPerWeek",
    questionNumber: 41,
    pageNumber: 8,
    x: 130, y: 660,
    fieldType: "text",
    label: "Hours Per Week",
    section: "work",
    lumaQuestion: "How many hours do you work per week?",
    required: true,
    skipIf: { field: "currentlyWorking", equals: "No", goTo: 43 },
  },
  {
    id: "weeklyPay",
    questionNumber: 42,
    pageNumber: 8,
    x: 130, y: 635,
    fieldType: "text",
    label: "Weekly Pay (before tax)",
    section: "work",
    lumaQuestion: "How much do you get paid each week before tax?",
    lumaExplanation: "An approximate amount is fine. This is your gross pay — the amount before any deductions.",
    required: true,
    skipIf: { field: "currentlyWorking", equals: "No", goTo: 43 },
  },
  {
    id: "lastWorkedDate",
    questionNumber: 43,
    pageNumber: 8,
    x: 130, y: 600,
    fieldType: "date",
    label: "Date Last Worked",
    section: "work",
    lumaQuestion: "When did you last work? An approximate date is fine. If you have never worked, say \"never\".",
    required: false,
    skipText: "never",
    dateBoxes: { ddX: 130, ddY: 600, mmX: 165, mmY: 600, yyyyX: 200, yyyyY: 600 },
  },
  {
    id: "lookingForWork",
    questionNumber: 44,
    pageNumber: 9,
    x: 130, y: 710,
    fieldType: "select",
    label: "Looking For Work",
    section: "work",
    options: ["Yes", "No"],
    lumaQuestion: "Are you currently looking for work?",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 710 },
      "No": { x: 180, y: 710 },
    },
  },
  {
    id: "workCapacity",
    questionNumber: 45,
    pageNumber: 9,
    x: 130, y: 680,
    fieldType: "select",
    label: "Able to Work 15+ Hours",
    section: "work",
    options: ["Yes", "No", "Not sure"],
    lumaQuestion: "Do you think you could work 15 or more hours a week in any kind of job?",
    lumaExplanation: "Be honest — there is no wrong answer. Your medical report will help Centrelink assess this.",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 680 },
      "No": { x: 180, y: 680 },
      "Not sure": { x: 230, y: 680 },
    },
  },

  // ────────────────────────────────────────────
  // PART F — INCOME AND ASSETS (pages 12-18)
  // ────────────────────────────────────────────
  {
    id: "ownHome",
    questionNumber: 46,
    pageNumber: 10,
    x: 130, y: 710,
    fieldType: "select",
    label: "Own Your Home",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Do you own the home you live in — either by yourself or with someone else?",
    lumaExplanation: "This includes owning with a mortgage (home loan).",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 710 },
      "No": { x: 180, y: 710 },
    },
  },
  {
    id: "rentAmount",
    questionNumber: 47,
    pageNumber: 10,
    x: 130, y: 680,
    fieldType: "text",
    label: "Weekly Rent Amount",
    section: "income",
    lumaQuestion: "How much rent do you pay each week? If you don't pay rent, say \"none\".",
    required: false,
    skipIf: { field: "ownHome", equals: "Yes", goTo: 48 },
    skipText: "none",
  },
  {
    id: "bankBalance",
    questionNumber: 48,
    pageNumber: 10,
    x: 130, y: 650,
    fieldType: "text",
    label: "Total Bank Balance",
    section: "income",
    lumaQuestion: "What is the total amount of money in all your bank accounts right now?",
    lumaExplanation: "Add up all your savings and everyday accounts. An approximate total is fine.",
    required: true,
  },
  {
    id: "hasShares",
    questionNumber: 49,
    pageNumber: 11,
    x: 130, y: 710,
    fieldType: "select",
    label: "Own Shares or Investments",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Do you own any shares, managed funds, or other investments?",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 710 },
      "No": { x: 180, y: 710 },
    },
  },
  {
    id: "sharesValue",
    questionNumber: 50,
    pageNumber: 11,
    x: 130, y: 685,
    fieldType: "text",
    label: "Shares/Investments Value",
    section: "income",
    lumaQuestion: "What is the approximate total value of your shares or investments?",
    required: true,
    skipIf: { field: "hasShares", equals: "No", goTo: 51 },
  },
  {
    id: "hasSuperannuation",
    questionNumber: 51,
    pageNumber: 11,
    x: 130, y: 655,
    fieldType: "select",
    label: "Have Superannuation",
    section: "income",
    options: ["Yes", "No", "Not sure"],
    lumaQuestion: "Do you have any superannuation (super)?",
    lumaExplanation: "Super is money that your employer saved for your retirement. If you have ever worked in Australia, you probably have some.",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 655 },
      "No": { x: 180, y: 655 },
      "Not sure": { x: 230, y: 655 },
    },
  },
  {
    id: "superFundName",
    questionNumber: 52,
    pageNumber: 11,
    x: 130, y: 625,
    fieldType: "text",
    label: "Super Fund Name",
    section: "income",
    lumaQuestion: "What is the name of your super fund? If you don't know, say \"don't know\".",
    required: false,
    skipIf: { field: "hasSuperannuation", equals: "No", goTo: 53 },
    skipText: "don't know",
  },
  {
    id: "hasVehicle",
    questionNumber: 53,
    pageNumber: 12,
    x: 130, y: 710,
    fieldType: "select",
    label: "Own a Vehicle",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Do you own a car, van, or other vehicle?",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 710 },
      "No": { x: 180, y: 710 },
    },
  },
  {
    id: "vehicleDetails",
    questionNumber: 54,
    pageNumber: 12,
    x: 130, y: 685,
    fieldType: "text",
    label: "Vehicle Details",
    section: "income",
    lumaQuestion: "What type of vehicle is it and approximately how much is it worth? For example, 'Toyota Corolla 2015, worth about $8,000'.",
    required: true,
    skipIf: { field: "hasVehicle", equals: "No", goTo: 55 },
    maxWidth: 350,
  },
  {
    id: "receivingCompensation",
    questionNumber: 55,
    pageNumber: 12,
    x: 130, y: 650,
    fieldType: "select",
    label: "Receiving Compensation",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Have you received or are you expecting any compensation payments? For example, from a work injury, car accident, or legal claim.",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 650 },
      "No": { x: 180, y: 650 },
    },
  },
  {
    id: "compensationDetails",
    questionNumber: 56,
    pageNumber: 12,
    x: 130, y: 620,
    fieldType: "text",
    label: "Compensation Details",
    section: "income",
    lumaQuestion: "Please describe the compensation — what is it for and how much?",
    required: true,
    skipIf: { field: "receivingCompensation", equals: "No", goTo: 57 },
    maxWidth: 350,
  },

  // ────────────────────────────────────────────
  // PART G — PARTNER DETAILS (pages 18-20)
  // ────────────────────────────────────────────
  {
    id: "hasPartner",
    questionNumber: 57,
    pageNumber: 15,
    x: 130, y: 710,
    fieldType: "select",
    label: "Have a Partner",
    section: "partner",
    options: ["Yes", "No"],
    lumaQuestion: "Do you have a partner? This means a husband, wife, or de facto partner you live with.",
    lumaExplanation: "A de facto partner is someone you live with in a relationship, even if you are not married.",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 710 },
      "No": { x: 180, y: 710 },
    },
  },
  {
    id: "partnerName",
    questionNumber: 58,
    pageNumber: 15,
    x: 130, y: 685,
    fieldType: "text",
    label: "Partner's Full Name",
    section: "partner",
    lumaQuestion: "What is your partner's full name?",
    required: true,
    skipIf: { field: "hasPartner", equals: "No", goTo: 65 },
    maxWidth: 300,
  },
  {
    id: "partnerDob",
    questionNumber: 59,
    pageNumber: 15,
    x: 130, y: 660,
    fieldType: "date",
    label: "Partner's Date of Birth",
    section: "partner",
    lumaQuestion: "What is your partner's date of birth?",
    required: true,
    skipIf: { field: "hasPartner", equals: "No", goTo: 65 },
    dateBoxes: { ddX: 130, ddY: 660, mmX: 165, mmY: 660, yyyyX: 200, yyyyY: 660 },
  },
  {
    id: "partnerCrn",
    questionNumber: 60,
    pageNumber: 15,
    x: 130, y: 635,
    fieldType: "text",
    label: "Partner's CRN",
    section: "partner",
    lumaQuestion: "Does your partner have a Centrelink Customer Reference Number? If not, say \"none\".",
    required: false,
    skipIf: { field: "hasPartner", equals: "No", goTo: 65 },
    skipText: "none",
  },
  {
    id: "partnerWorking",
    questionNumber: 61,
    pageNumber: 15,
    x: 130, y: 610,
    fieldType: "select",
    label: "Partner Working",
    section: "partner",
    options: ["Yes", "No"],
    lumaQuestion: "Is your partner currently working?",
    required: true,
    skipIf: { field: "hasPartner", equals: "No", goTo: 65 },
    tickPositions: {
      "Yes": { x: 130, y: 610 },
      "No": { x: 180, y: 610 },
    },
  },
  {
    id: "partnerIncome",
    questionNumber: 62,
    pageNumber: 15,
    x: 130, y: 585,
    fieldType: "text",
    label: "Partner's Weekly Income",
    section: "partner",
    lumaQuestion: "How much does your partner earn per week before tax?",
    required: true,
    skipIf: { field: "partnerWorking", equals: "No", goTo: 63 },
  },
  {
    id: "partnerReceivingPayment",
    questionNumber: 63,
    pageNumber: 16,
    x: 130, y: 710,
    fieldType: "select",
    label: "Partner Receiving Payment",
    section: "partner",
    options: ["Yes", "No"],
    lumaQuestion: "Is your partner receiving any Centrelink payments?",
    required: true,
    skipIf: { field: "hasPartner", equals: "No", goTo: 65 },
    tickPositions: {
      "Yes": { x: 130, y: 710 },
      "No": { x: 180, y: 710 },
    },
  },
  {
    id: "partnerPaymentType",
    questionNumber: 64,
    pageNumber: 16,
    x: 130, y: 685,
    fieldType: "text",
    label: "Partner's Payment Type",
    section: "partner",
    lumaQuestion: "What payment is your partner receiving?",
    required: true,
    skipIf: { field: "partnerReceivingPayment", equals: "No", goTo: 65 },
  },

  // ────────────────────────────────────────────
  // PART H — BANK ACCOUNT DETAILS (pages 20-21)
  // ────────────────────────────────────────────
  {
    id: "bankName",
    questionNumber: 65,
    pageNumber: 17,
    x: 130, y: 710,
    fieldType: "text",
    label: "Bank Name",
    section: "bank",
    lumaQuestion: "What is the name of your bank? For example, Commonwealth Bank, ANZ, Westpac.",
    required: true,
  },
  {
    id: "bsb",
    questionNumber: 66,
    pageNumber: 17,
    x: 130, y: 685,
    fieldType: "text",
    label: "BSB Number",
    section: "bank",
    lumaQuestion: "What is your BSB number? It is a 6-digit number — you can find it on your bank statement or app.",
    required: true,
  },
  {
    id: "accountNumber",
    questionNumber: 67,
    pageNumber: 17,
    x: 130, y: 660,
    fieldType: "text",
    label: "Account Number",
    section: "bank",
    lumaQuestion: "What is your bank account number?",
    required: true,
  },
  {
    id: "accountName",
    questionNumber: 68,
    pageNumber: 17,
    x: 130, y: 635,
    fieldType: "text",
    label: "Account Holder Name",
    section: "bank",
    lumaQuestion: "What name is the bank account in?",
    lumaExplanation: "This is the name shown on the account — it should match your name or be a joint account with your partner.",
    required: true,
    maxWidth: 250,
  },
  {
    id: "accountType",
    questionNumber: 69,
    pageNumber: 17,
    x: 130, y: 610,
    fieldType: "select",
    label: "Account Type",
    section: "bank",
    options: ["Savings", "Cheque"],
    lumaQuestion: "Is this a savings account or a cheque (everyday) account?",
    required: true,
    tickPositions: {
      "Savings": { x: 130, y: 610 },
      "Cheque": { x: 200, y: 610 },
    },
  },

  // ────────────────────────────────────────────
  // PART I — DECLARATION (pages 33-36)
  // ────────────────────────────────────────────
  {
    id: "declarationDate",
    questionNumber: 70,
    pageNumber: 33,
    x: 130, y: 300,
    fieldType: "date",
    label: "Declaration Date",
    section: "declaration",
    lumaQuestion: "Today's date will be used for the declaration. Shall I use today's date?",
    lumaExplanation: "This is the date you are signing and submitting this form.",
    required: true,
    dateBoxes: { ddX: 130, ddY: 300, mmX: 165, mmY: 300, yyyyX: 200, yyyyY: 300 },
  },
  {
    id: "declarationSignature",
    questionNumber: 71,
    pageNumber: 33,
    x: 130, y: 260,
    fieldType: "text",
    label: "Signature",
    section: "declaration",
    lumaQuestion: "Almost done! ✍️",
    signatureNotice: "You will need to sign this section by hand after you print the form. Just write your signature in the box on the last page.",
    required: false,
  },
  {
    id: "declarationComplete",
    questionNumber: 72,
    pageNumber: 33,
    x: 0, y: 0,
    fieldType: "text",
    label: "Confirmation",
    section: "declaration",
    lumaQuestion: "You have completed the entire form! 🎉 Your Disability Support Pension form is ready to download, print, sign, and post to Centrelink at: Reply Paid 7800, Canberra BC ACT 2610.",
    required: false,
  },
];
