/**
 * SA466 Disability Support Pension Claim — Complete Field Map
 *
 * Every field the form asks for, with:
 *   - questionNumber: order Luma follows
 *   - pageNumber: 0-based PDF page
 *   - x, y: PDF coordinates (origin bottom-left, A4 595×842pt)
 *   - fieldType: "text" | "tick" | "date" | "select"
 *   - lumaQuestion: plain-language question Luma asks
 *   - lumaExplanation?: optional explainer before the question
 *   - options?: for select / tick fields
 *   - required: whether the field must be answered
 *   - skipIf?: { field: string; equals: string; goTo: number } — skip logic
 *   - signatureNotice?: string — tells user to sign by hand
 *   - skipText?: hint for optional fields
 *   - maxWidth?: for long text wrapping
 */

export interface SA466Field {
  id: string;
  questionNumber: number;
  pageNumber: number;
  x: number;
  y: number;
  fieldType: "text" | "tick" | "date" | "select";
  lumaQuestion: string;
  lumaExplanation?: string;
  options?: string[];
  required: boolean;
  skipIf?: { field: string; equals: string; goTo: number };
  skipIfValues?: string[];  // Multiple skip trigger values
  signatureNotice?: string;
  skipText?: string;
  maxWidth?: number;
  // For date fields: individual box positions for DD, MM, YYYY
  dateBoxes?: { ddX: number; ddY: number; mmX: number; mmY: number; yyyyX: number; yyyyY: number };
  // For tick fields: positions for each option value
  tickPositions?: Record<string, { x: number; y: number }>;
  label: string;
  section: string;
}

export const SA466_SECTIONS = [
  { id: "personal", title: "Part A — Your Personal Details", startQ: 1, endQ: 14 },
  { id: "residence", title: "Part B — Your Residence", startQ: 15, endQ: 22 },
  { id: "payment", title: "Part C — Payment Details", startQ: 23, endQ: 27 },
  { id: "disability", title: "Part D — Your Disability or Medical Condition", startQ: 28, endQ: 38 },
  { id: "work", title: "Part E — Your Work History", startQ: 39, endQ: 45 },
  { id: "income", title: "Part F — Income and Assets", startQ: 46, endQ: 56 },
  { id: "partner", title: "Part G — Your Partner", startQ: 57, endQ: 64 },
  { id: "bank", title: "Part H — Bank Account Details", startQ: 65, endQ: 69 },
  { id: "declaration", title: "Part I — Declaration", startQ: 70, endQ: 72 },
] as const;

export const SA466_FIELDS: SA466Field[] = [
  // ────────────────────────────────────────────
  // PART A — PERSONAL DETAILS (pages 1-3)
  // ────────────────────────────────────────────
  // ── PAGE 7 (pageNumber: 6) — Personal Details ──
  // y values are TOP offsets: actual PDF y = pageHeight - y
  {
    id: "title",
    questionNumber: 1,
    pageNumber: 6,
    x: 64, y: 412,
    fieldType: "select",
    label: "Title",
    section: "personal",
    options: ["Mr", "Mrs", "Ms", "Miss", "Dr"],
    lumaQuestion: "First up — how would you like to be addressed? 😊",
    required: true,
    tickPositions: {
      "Mr":   { x: 64,  y: 412 },
      "Mrs":  { x: 97,  y: 412 },
      "Ms":   { x: 164, y: 412 },
      "Miss": { x: 134, y: 412 },
      "Dr":   { x: 193, y: 411 },
    },
  },
  {
    id: "familyName",
    questionNumber: 2,
    pageNumber: 6,
    x: 51, y: 376,
    fieldType: "text",
    label: "Family Name",
    section: "personal",
    lumaQuestion: "What is your family name (surname)?",
    required: true,
    maxWidth: 200,
  },
  {
    id: "firstName",
    questionNumber: 3,
    pageNumber: 6,
    x: 51, y: 341,
    fieldType: "text",
    label: "First Name",
    section: "personal",
    lumaQuestion: "And your first (given) name?",
    required: true,
    maxWidth: 200,
  },
  {
    id: "secondName",
    questionNumber: 4,
    pageNumber: 6,
    x: 51, y: 305,
    fieldType: "text",
    label: "Second/Middle Name",
    section: "personal",
    lumaQuestion: "Do you have a middle or second name? If not, just say \"none\" 😊",
    required: false,
    skipText: "none",
    maxWidth: 200,
  },
  {
    id: "otherNames",
    questionNumber: 5,
    pageNumber: 6,
    x: 339, y: 603,
    fieldType: "text",
    label: "Other Names Used",
    section: "personal",
    lumaQuestion: "Have you ever used a different name? For example, your name before marriage, or a nickname on official documents?",
    lumaExplanation: "The government needs this to check their records under any name you may have used before.",
    required: false,
    skipText: "none",
    maxWidth: 200,
  },
  {
    id: "dob",
    questionNumber: 6,
    pageNumber: 6,
    x: 52, y: 254,
    fieldType: "date",
    label: "Date of Birth",
    section: "personal",
    lumaQuestion: "What is your date of birth? You can type it as DD/MM/YYYY 📅",
    required: true,
    dateBoxes: { ddX: 52, ddY: 254, mmX: 85, mmY: 254, yyyyX: 120, yyyyY: 254 },
  },
  {
    id: "gender",
    questionNumber: 7,
    pageNumber: 6,
    x: 147, y: 296,
    fieldType: "select",
    label: "Gender",
    section: "personal",
    options: ["Male", "Female", "Other"],
    lumaQuestion: "What is your gender?",
    lumaExplanation: "This is for the government's records only — choose whichever feels right for you.",
    required: true,
    tickPositions: {
      "Male":   { x: 379, y: 396 },
      "Female": { x: 379, y: 381 },
      "Other":  { x: 379, y: 365 },
    },
  },
  {
    id: "permanentAddress",
    fieldSubtype: "address",
    questionNumber: 8,
    pageNumber: 6,
    x: 335, y: 222,
    fieldType: "text",
    label: "Home Address",
    section: "personal",
    lumaQuestion: "What is your home address? Include street number, street name, suburb, and state 🏠",
    lumaExplanation: "This is the address where you actually live — not a PO Box.",
    required: true,
    maxWidth: 300,
  },
  {
    id: "postcode",
    questionNumber: 9,
    pageNumber: 6,
    x: 506, y: 182,
    fieldType: "text",
    label: "Postcode",
    section: "personal",
    lumaQuestion: "And your postcode?",
    required: true,
  },
  {
    id: "postalAddressSame",
    questionNumber: 10,
    pageNumber: 6,
    x: 147, y: 370,
    fieldType: "select",
    label: "Postal Address Same?",
    section: "personal",
    options: ["Yes", "No"],
    lumaQuestion: "Is your postal address the same as your home address?",
    lumaExplanation: "Your postal address is where you want to receive letters from the government.",
    required: true,
    // No checkbox exists for postal same - controlled via skip logic in prefill
    tickPositions: undefined,
  },
  {
    id: "postalAddress",
    fieldSubtype: "address",
    questionNumber: 11,
    pageNumber: 6,
    x: 335, y: 222,
    fieldType: "text",
    label: "Postal Address",
    section: "personal",
    lumaQuestion: "What is your postal address?",
    required: true,
    skipIf: { field: "postalAddressSame", equals: "Yes", goTo: 12 },
    maxWidth: 300,
  },

  // ── PAGE 8 (pageNumber: 7) — Contact Details ──
  {
    id: "homePhone",
    questionNumber: 12,
    pageNumber: 7,
    x: 89, y: 675,
    fieldType: "text",
    label: "Home Phone",
    section: "personal",
    lumaQuestion: "Do you have a home phone number? If not, just say \"none\" 📞",
    required: false,
    skipText: "none",
  },
  {
    id: "mobile",
    questionNumber: 13,
    pageNumber: 7,
    x: 143, y: 696,
    fieldType: "text",
    label: "Mobile Number",
    section: "personal",
    lumaQuestion: "What is your mobile phone number? 📱",
    required: true,
  },
  {
    id: "email",
    questionNumber: 14,
    pageNumber: 7,
    x: 51, y: 660,
    fieldType: "text",
    label: "Email Address",
    section: "personal",
    lumaQuestion: "What is your email address? If you don't have one, just say \"none\" ✉️",
    required: false,
    skipText: "none",
    maxWidth: 250,
  },

  // ────────────────────────────────────────────
  // PART B — RESIDENCE (pages 3-5)
  // ────────────────────────────────────────────
  {
    id: "crn",
    questionNumber: 15,
    pageNumber: 6,
    x: 50, y: 461,
    fieldType: "text",
    label: "Customer Reference Number",
    section: "residence",
    lumaQuestion: "Do you have a Centrelink Customer Reference Number (CRN)?",
    lumaExplanation: "This is a 9-digit number on your Centrelink card. If you have never had a Centrelink card or don't know your number, just say \"none\" — that is perfectly fine!",
    required: false,
    skipText: "none",
  },
  {
    id: "australianCitizen",
    questionNumber: 16,
    pageNumber: 11,
    x: 67, y: 515,
    fieldType: "select",
    label: "Australian Citizen",
    section: "residence",
    options: ["Yes", "No"],
    lumaQuestion: "Are you an Australian citizen?",
    required: true,
    tickPositions: {
      "Yes": { x: 67, y: 515 },
    
      "No":  { x: 38, y: 538 },
    },
  },
  {
    id: "permanentResident",
    questionNumber: 17,
    pageNumber: 11,
    x: 67, y: 515,
    fieldType: "select",
    label: "Permanent Resident",
    section: "residence",
    options: ["Yes", "No"],
    lumaQuestion: "Are you a permanent resident of Australia?",
    lumaExplanation: "A permanent resident has a visa that lets them live in Australia permanently.",
    required: true,
    skipIf: { field: "australianCitizen", equals: "Yes", goTo: 19 },
    tickPositions: {
      "Yes": { x: 67, y: 515 },
    
      "No":  { x: 180, y: 655 },
    },
  },
  {
    id: "visaType",
    questionNumber: 18,
    pageNumber: 12,
    x: 51, y: 670,
    fieldType: "text",
    label: "Visa Type/Number",
    section: "residence",
    lumaQuestion: "What type of visa do you have? If you know the visa number, please include it.",
    required: false,
    skipIf: { field: "australianCitizen", equals: "Yes", goTo: 19 },
    skipText: "don't know",
  },
  {
    id: "arrivalDate",
    questionNumber: 19,
    pageNumber: 11,
    x: 335, y: 138,
    fieldType: "date",
    label: "Date of Arrival in Australia",
    section: "residence",
    lumaQuestion: "When did you first arrive in Australia? Type the date as DD/MM/YYYY. If you were born here, say \"born here\".",
    required: false,
    skipText: "born here",
    dateBoxes: { ddX: 130, ddY: 600, mmX: 165, mmY: 600, yyyyX: 200, yyyyY: 600 },
  },
  {
    id: "countryOfBirth",
    questionNumber: 20,
    pageNumber: 11,
    x: 335, y: 447,
    fieldType: "text",
    label: "Country of Birth",
    section: "residence",
    lumaQuestion: "What country were you born in?",
    required: true,
  },
  {
    id: "travelledOverseas",
    questionNumber: 21,
    pageNumber: 12,
    x: 67, y: 605,
    fieldType: "select",
    label: "Travelled Overseas",
    section: "residence",
    options: ["Yes", "No"],
    lumaQuestion: "Have you travelled outside Australia in the last 12 months?",
    required: true,
    tickPositions: {
      "Yes": { x: 67, y: 605 },
    
      "No":  { x: 180, y: 710 },
    },
  },
  {
    id: "travelDates",
    questionNumber: 22,
    pageNumber: 12,
    x: 51, y: 468,
    fieldType: "text",
    label: "Travel Dates",
    section: "residence",
    lumaQuestion: "What dates were you overseas? Please tell me the dates you left and returned.",
    required: true,
    skipIf: { field: "travelledOverseas", equals: "No", goTo: 23 },
    maxWidth: 350,
  },

  // ────────────────────────────────────────────
  // PART C — PAYMENT DETAILS (pages 5-6)
  // ────────────────────────────────────────────
  {
    id: "taxFileNumber",
    questionNumber: 23,
    pageNumber: 10,
    x: 51, y: 427,
    fieldType: "text",
    label: "Tax File Number",
    section: "payment",
    lumaQuestion: "What is your Tax File Number (TFN)?",
    lumaExplanation: "Your TFN is a 9-digit number from the tax office. If you don't have one or don't know it, say \"none\" — Centrelink can look it up.",
    required: false,
    skipText: "none",
  },
  {
    id: "receivingPayment",
    questionNumber: 24,
    pageNumber: 11,
    x: 67, y: 515,
    fieldType: "select",
    label: "Currently Receiving Payment",
    section: "payment",
    options: ["Yes", "No"],
    lumaQuestion: "Are you currently receiving any payments from Centrelink?",
    lumaExplanation: "This includes JobSeeker, Youth Allowance, Carer Payment, or any other government payment.",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 680 },
    },
  },
  {
    id: "currentPaymentType",
    questionNumber: 25,
    pageNumber: 11,
    x: 335, y: 282,
    fieldType: "text",
    label: "Current Payment Type",
    section: "payment",
    lumaQuestion: "What payment are you currently receiving?",
    required: true,
    skipIf: { field: "receivingPayment", equals: "No", goTo: 26 },
  },
  {
    id: "claimStartDate",
    questionNumber: 26,
    pageNumber: 11,
    x: 390, y: 211,
    fieldType: "date",
    label: "Claim Start Date",
    section: "payment",
    lumaQuestion: "From what date do you want this Disability Support Pension to start? If you want it to start from today, say \"today\".",
    lumaExplanation: "Usually this is today's date or the date you became unable to work due to your condition.",
    required: true,
    dateBoxes: { ddX: 130, ddY: 625, mmX: 165, mmY: 625, yyyyX: 200, yyyyY: 625 },
  },
  {
    id: "interpreterNeeded",
    questionNumber: 27,
    pageNumber: 7,
    x: 67, y: 575,
    fieldType: "select",
    label: "Interpreter Needed",
    section: "payment",
    options: ["Yes", "No"],
    lumaQuestion: "Do you need an interpreter when dealing with Centrelink?",
    lumaExplanation: "If you are more comfortable speaking in a language other than English, Centrelink can arrange a free interpreter for you.",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 595 },
    },
  },

  // ────────────────────────────────────────────
  // PART D — DISABILITY / MEDICAL CONDITION (pages 6-10)
  // ────────────────────────────────────────────
  {
    id: "primaryCondition",
    questionNumber: 28,
    pageNumber: 29,
    x: 54, y: 400,
    fieldType: "text",
    label: "Primary Medical Condition",
    section: "disability",
    lumaQuestion: "What is your main medical condition, disability, or injury?",
    lumaExplanation: "This is the condition that most affects your ability to work. Just describe it in your own words — for example, 'back injury' or 'depression and anxiety'.",
    required: true,
    maxWidth: 350,
  },
  {
    id: "conditionStartDate",
    questionNumber: 29,
    pageNumber: 29,
    x: 52, y: 49,
    fieldType: "date",
    label: "Condition Start Date",
    section: "disability",
    lumaQuestion: "When did this condition first start? An approximate date is fine — for example, \"March 2019\" or \"about 5 years ago\".",
    required: true,
    dateBoxes: { ddX: 130, ddY: 680, mmX: 165, mmY: 680, yyyyX: 200, yyyyY: 680 },
  },
  {
    id: "otherConditions",
    questionNumber: 30,
    pageNumber: 29,
    x: 54, y: 300,
    fieldType: "text",
    label: "Other Medical Conditions",
    section: "disability",
    lumaQuestion: "Do you have any other medical conditions, disabilities, or injuries? If not, say \"none\".",
    required: false,
    skipText: "none",
    maxWidth: 350,
  },
  {
    id: "treatingDoctor",
    questionNumber: 31,
    pageNumber: 33,
    x: 59, y: 701,
    fieldType: "text",
    label: "Treating Doctor's Name",
    section: "disability",
    lumaQuestion: "What is the name of your main doctor who treats your condition?",
    required: true,
    maxWidth: 250,
  },
  {
    id: "doctorAddress",
    fieldSubtype: "address",
    questionNumber: 31,
    pageNumber: 33,
    x: 58, y: 633,
    fieldType: "text",
    label: "Doctor's Address",
    section: "disability",
    lumaQuestion: "What is the address or clinic name of your doctor?",
    required: true,
    maxWidth: 350,
  },
  {
    id: "doctorPhone",
    questionNumber: 32,
    pageNumber: 33,
    x: 56, y: 558,
    fieldType: "text",
    label: "Doctor's Phone",
    section: "disability",
    lumaQuestion: "What is your doctor's phone number?",
    required: false,
    skipText: "don't know",
  },
  {
    id: "doctorProfession",
    questionNumber: 32,
    pageNumber: 33,
    x: 59, y: 667,
    fieldType: "text",
    label: "Doctor's Profession",
    section: "disability",
    lumaQuestion: "What type of doctor is this? For example: GP, Psychiatrist, Physiotherapist.",
    required: false,
    skipText: "GP",
    maxWidth: 250,
  },
  {
    id: "doctor2Name",
    questionNumber: 33,
    pageNumber: 33,
    x: 59, y: 511,
    fieldType: "text",
    label: "Second Doctor's Name",
    section: "disability",
    lumaQuestion: "Do you have a second doctor or specialist who treats your condition? If so, what is their name? Say \"none\" if not.",
    required: false,
    skipText: "none",
    skipIfValues: ["none", "no", "n/a"],
    maxWidth: 250,
  },
  {
    id: "doctor2Profession",
    questionNumber: 33,
    pageNumber: 33,
    x: 59, y: 477,
    fieldType: "text",
    label: "Second Doctor's Profession",
    section: "disability",
    lumaQuestion: "What type of specialist is your second doctor? For example: Psychiatrist, Neurologist.",
    required: false,
    skipText: "none",
    maxWidth: 250,
    skipIf: { field: "doctor2Name", equals: "none", goTo: 34 },
  },
  {
    id: "doctor2Address",
    fieldSubtype: "address",
    questionNumber: 33,
    pageNumber: 33,
    x: 58, y: 443,
    fieldType: "text",
    label: "Second Doctor's Address",
    section: "disability",
    lumaQuestion: "What is the clinic or address for your second doctor?",
    required: false,
    skipText: "none",
    maxWidth: 350,
    skipIf: { field: "doctor2Name", equals: "none", goTo: 34 },
  },
  {
    id: "doctor2Phone",
    questionNumber: 33,
    pageNumber: 33,
    x: 56, y: 368,
    fieldType: "text",
    label: "Second Doctor's Phone",
    section: "disability",
    lumaQuestion: "What is the phone number for your second doctor?",
    required: false,
    skipText: "none",
    skipIf: { field: "doctor2Name", equals: "none", goTo: 34 },
  },


  {
    id: "doctor3Name",
    questionNumber: 34,
    pageNumber: 33,
    x: 57, y: 321,
    fieldType: "text",
    label: "Third Doctor's Name",
    section: "disability",
    lumaQuestion: "Do you have a third doctor or specialist? If so, what is their name? Say \"none\" if not.",
    required: false,
    skipText: "none",
    skipIfValues: ["none", "no", "n/a"],
    maxWidth: 250,
    skipIf: { field: "doctor2Name", equals: "none", goTo: 35 },
  },
  {
    id: "doctor3Profession",
    questionNumber: 34,
    pageNumber: 33,
    x: 57, y: 287,
    fieldType: "text",
    label: "Third Doctor's Profession",
    section: "disability",
    lumaQuestion: "What type of specialist is your third doctor?",
    required: false,
    skipText: "none",
    maxWidth: 250,
    skipIf: { field: "doctor3Name", equals: "none", goTo: 35 },
  },
  {
    id: "doctor3Address",
    fieldSubtype: "address",
    questionNumber: 34,
    pageNumber: 33,
    x: 56, y: 252,
    fieldType: "text",
    label: "Third Doctor's Address",
    section: "disability",
    lumaQuestion: "What is the clinic or address for your third doctor?",
    required: false,
    skipText: "none",
    maxWidth: 350,
    skipIf: { field: "doctor3Name", equals: "none", goTo: 35 },
  },
  {
    id: "doctor3Phone",
    questionNumber: 34,
    pageNumber: 33,
    x: 54, y: 177,
    fieldType: "text",
    label: "Third Doctor's Phone",
    section: "disability",
    lumaQuestion: "What is the phone number for your third doctor?",
    required: false,
    skipText: "none",
    skipIf: { field: "doctor3Name", equals: "none", goTo: 35 },
  },
  {
    id: "hospitalised",
    questionNumber: 34,
    pageNumber: 29,
    x: 67, y: 763,
    fieldType: "select",
    label: "Hospitalised Recently",
    section: "disability",
    options: ["Yes", "No"],
    lumaQuestion: "Have you been in hospital because of your condition in the last 12 months?",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 710 },
    },
  },
  {
    id: "hospitalDetails",
    questionNumber: 35,
    pageNumber: 29,
    x: 54, y: 300,
    fieldType: "text",
    label: "Hospital Details",
    section: "disability",
    lumaQuestion: "Which hospital were you in and when?",
    required: true,
    skipIf: { field: "hospitalised", equals: "No", goTo: 36 },
    maxWidth: 350,
  },
  {
    id: "medication",
    questionNumber: 36,
    pageNumber: 29,
    x: 54, y: 200,
    fieldType: "text",
    label: "Current Medications",
    section: "disability",
    lumaQuestion: "What medications are you currently taking? If none, say \"none\".",
    lumaExplanation: "List all medicines you take regularly, including any over-the-counter or herbal medicines.",
    required: false,
    skipText: "none",
    maxWidth: 350,
  },
  {
    id: "mobilityAids",
    questionNumber: 37,
    pageNumber: 29,
    x: 54, y: 150,
    fieldType: "text",
    label: "Mobility Aids",
    section: "disability",
    lumaQuestion: "Do you use any aids or equipment because of your condition? For example, a wheelchair, walking stick, hearing aid. If none, say \"none\".",
    required: false,
    skipText: "none",
    maxWidth: 350,
  },
  {
    id: "conditionPermanent",
    questionNumber: 38,
    pageNumber: 29,
    x: 67, y: 763,
    fieldType: "select",
    label: "Condition Permanent",
    section: "disability",
    options: ["Yes", "No", "Not sure"],
    lumaQuestion: "Is your condition likely to be permanent? That means it will probably not get better even with treatment.",
    lumaExplanation: "It is okay to say 'not sure' — your doctor's report will help Centrelink decide this.",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 575 },
      "No": { x: 180, y: 575 },
      "Not sure": { x: 230, y: 575 },
    },
  },

  // ────────────────────────────────────────────
  // PART E — WORK HISTORY (pages 10-12)
  // ────────────────────────────────────────────
  {
    id: "currentlyWorking",
    questionNumber: 39,
    pageNumber: 7,
    x: 350, y: 690,
    fieldType: "select",
    label: "Currently Working",
    section: "work",
    options: ["Yes", "No"],
    lumaQuestion: "Are you currently working at all — even a few hours a week?",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 710 },
    },
  },
  {
    id: "employerName",
    questionNumber: 40,
    pageNumber: 22,
    x: 339, y: 355,
    fieldType: "text",
    label: "Employer Name",
    section: "work",
    lumaQuestion: "What is the name of your employer?",
    required: true,
    skipIf: { field: "currentlyWorking", equals: "No", goTo: 43 },
    maxWidth: 250,
  },
  {
    id: "hoursPerWeek",
    questionNumber: 41,
    pageNumber: 22,
    x: 339, y: 480,
    fieldType: "text",
    label: "Hours Per Week",
    section: "work",
    lumaQuestion: "How many hours do you work per week?",
    required: true,
    skipIf: { field: "currentlyWorking", equals: "No", goTo: 43 },
  },
  {
    id: "weeklyPay",
    questionNumber: 42,
    pageNumber: 22,
    x: 339, y: 480,
    fieldType: "text",
    label: "Weekly Pay (before tax)",
    section: "work",
    lumaQuestion: "How much do you get paid each week before tax?",
    lumaExplanation: "An approximate amount is fine. This is your gross pay — the amount before any deductions.",
    required: true,
    skipIf: { field: "currentlyWorking", equals: "No", goTo: 43 },
  },
  {
    id: "lastWorkedDate",
    questionNumber: 43,
    pageNumber: 22,
    x: 337, y: 442,
    fieldType: "date",
    label: "Date Last Worked",
    section: "work",
    lumaQuestion: "When did you last work? An approximate date is fine. If you have never worked, say \"never\".",
    required: false,
    skipText: "never",
    dateBoxes: { ddX: 130, ddY: 600, mmX: 165, mmY: 600, yyyyX: 200, yyyyY: 600 },
  },
  {
    id: "lookingForWork",
    questionNumber: 44,
    pageNumber: 8,
    x: 350, y: 775,
    fieldType: "select",
    label: "Looking For Work",
    section: "work",
    options: ["Yes", "No"],
    lumaQuestion: "Are you currently looking for work?",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 710 },
    },
  },
  {
    id: "workCapacity",
    questionNumber: 45,
    pageNumber: 9,
    x: 67, y: 564,
    fieldType: "select",
    label: "Able to Work 15+ Hours",
    section: "work",
    options: ["Yes", "No", "Not sure"],
    lumaQuestion: "Do you think you could work 15 or more hours a week in any kind of job?",
    lumaExplanation: "Be honest — there is no wrong answer. Your medical report will help Centrelink assess this.",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 680 },
      "No": { x: 180, y: 680 },
      "Not sure": { x: 230, y: 680 },
    },
  },

  // ────────────────────────────────────────────
  // PART F — INCOME AND ASSETS (pages 12-18)
  // ────────────────────────────────────────────
  {
    id: "ownHome",
    questionNumber: 46,
    pageNumber: 18,
    x: 501, y: 660,
    fieldType: "select",
    label: "Own Your Home",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Do you own the home you live in — either by yourself or with someone else?",
    lumaExplanation: "This includes owning with a mortgage (home loan).",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 710 },
    },
  },
  {
    id: "rentAmount",
    questionNumber: 47,
    pageNumber: 18,
    x: 62, y: 354,
    fieldType: "text",
    label: "Weekly Rent Amount",
    section: "income",
    lumaQuestion: "How much rent do you pay each week? If you don't pay rent, say \"none\".",
    required: false,
    skipIf: { field: "ownHome", equals: "Yes", goTo: 48 },
    skipText: "none",
  },
  {
    id: "bankBalance",
    questionNumber: 48,
    pageNumber: 20,
    x: 335, y: 541,
    fieldType: "text",
    label: "Total Bank Balance",
    section: "income",
    lumaQuestion: "What is the total amount of money in all your bank accounts right now?",
    lumaExplanation: "Add up all your savings and everyday accounts. An approximate total is fine.",
    required: true,
  },
  {
    id: "hasShares",
    questionNumber: 49,
    pageNumber: 19,
    x: 350, y: 564,
    fieldType: "select",
    label: "Own Shares or Investments",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Do you own any shares, managed funds, or other investments?",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 710 },
    },
  },
  {
    id: "sharesValue",
    questionNumber: 50,
    pageNumber: 19,
    x: 344, y: 367,
    fieldType: "text",
    label: "Shares/Investments Value",
    section: "income",
    lumaQuestion: "What is the approximate total value of your shares or investments?",
    required: true,
    skipIf: { field: "hasShares", equals: "No", goTo: 51 },
  },
  {
    id: "hasSuperannuation",
    questionNumber: 51,
    pageNumber: 19,
    x: 350, y: 564,
    fieldType: "select",
    label: "Have Superannuation",
    section: "income",
    options: ["Yes", "No", "Not sure"],
    lumaQuestion: "Do you have any superannuation (super)?",
    lumaExplanation: "Super is money that your employer saved for your retirement. If you have ever worked in Australia, you probably have some.",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 655 },
      "No": { x: 180, y: 655 },
      "Not sure": { x: 230, y: 655 },
    },
  },
  {
    id: "superFundName",
    questionNumber: 52,
    pageNumber: 19,
    x: 344, y: 330,
    fieldType: "text",
    label: "Super Fund Name",
    section: "income",
    lumaQuestion: "What is the name of your super fund? If you don't know, say \"don't know\".",
    required: false,
    skipIf: { field: "hasSuperannuation", equals: "No", goTo: 53 },
    skipText: "don't know",
  },
  {
    id: "hasVehicle",
    questionNumber: 53,
    pageNumber: 20,
    x: 70, y: 707,
    fieldType: "select",
    label: "Own a Vehicle",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Do you own a car, van, or other vehicle?",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 710 },
    },
  },
  {
    id: "vehicleDetails",
    questionNumber: 54,
    pageNumber: 20,
    x: 335, y: 761,
    fieldType: "text",
    label: "Vehicle Details",
    section: "income",
    lumaQuestion: "What type of vehicle is it and approximately how much is it worth? For example, 'Toyota Corolla 2015, worth about $8,000'.",
    required: true,
    skipIf: { field: "hasVehicle", equals: "No", goTo: 55 },
    maxWidth: 350,
  },
  {
    id: "receivingCompensation",
    questionNumber: 55,
    pageNumber: 18,
    x: 351, y: 205,
    fieldType: "select",
    label: "Receiving Compensation",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Have you received or are you expecting any compensation payments? For example, from a work injury, car accident, or legal claim.",
    required: true,
    tickPositions: {
      "Yes": { x: 130, y: 650 },
    },
  },
  {
    id: "compensationDetails",
    questionNumber: 56,
    pageNumber: 18,
    x: 335, y: 282,
    fieldType: "text",
    label: "Compensation Details",
    section: "income",
    lumaQuestion: "Please describe the compensation — what is it for and how much?",
    required: true,
    skipIf: { field: "receivingCompensation", equals: "No", goTo: 57 },
    maxWidth: 350,
  },

  // ────────────────────────────────────────────
  // PART G — PARTNER DETAILS (pages 18-20)
  // ────────────────────────────────────────────
  {
    id: "hasPartner",
    questionNumber: 54,
    pageNumber: 13,
    x: 67, y: 762,
    fieldType: "select",
    label: "Have a Partner",
    section: "partner",
    options: ["Yes", "No"],
    lumaQuestion: "Do you have a partner? This means a husband, wife, or de facto partner you live with.",
    lumaExplanation: "A de facto partner is someone you live with in a relationship, even if you are not married.",
    required: true,
    tickPositions: {
      "Yes": { x: 67, y: 747 },
    
      "No":  { x: 180, y: 710 },
    },
  },
  {
    id: "partnerCrn",
    questionNumber: 60,
    pageNumber: 13,
    x: 50, y: 334,
    fieldType: "text",
    label: "Partner's CRN",
    section: "partner",
    lumaQuestion: "Does your partner have a Centrelink Customer Reference Number? If not, say \"none\".",
    required: false,
    skipIf: { field: "hasPartner", equals: "No", goTo: 65 },
    skipText: "none",
  },
  {
    id: "partnerWorking",
    questionNumber: 61,
    pageNumber: 13,
    x: 350, y: 749,
    fieldType: "select",
    label: "Partner Working",
    section: "partner",
    options: ["Yes", "No"],
    lumaQuestion: "Is your partner currently working?",
    required: true,
    skipIf: { field: "hasPartner", equals: "No", goTo: 65 },
    tickPositions: {
      "Yes": { x: 350, y: 749 },
    
      "No":  { x: 180, y: 610 },
    },
  },
  {
    id: "partnerIncome",
    questionNumber: 62,
    pageNumber: 13,
    x: 51, y: 213,
    fieldType: "text",
    label: "Partner's Weekly Income",
    section: "partner",
    lumaQuestion: "How much does your partner earn per week before tax?",
    required: true,
    skipIf: { field: "partnerWorking", equals: "No", goTo: 63 },
  },
  {
    id: "partnerReceivingPayment",
    questionNumber: 63,
    pageNumber: 13,
    x: 350, y: 765,
    fieldType: "select",
    label: "Partner Receiving Payment",
    section: "partner",
    options: ["Yes", "No"],
    lumaQuestion: "Is your partner receiving any Centrelink payments?",
    required: true,
    skipIf: { field: "hasPartner", equals: "No", goTo: 65 },
    tickPositions: {
      "Yes": { x: 130, y: 710 },
    },
  },
  {
    id: "partnerPaymentType",
    questionNumber: 64,
    pageNumber: 13,
    x: 51, y: 178,
    fieldType: "text",
    label: "Partner's Payment Type",
    section: "partner",
    lumaQuestion: "What payment is your partner receiving?",
    required: true,
    skipIf: { field: "partnerReceivingPayment", equals: "No", goTo: 65 },
  },

  // ────────────────────────────────────────────
  // PART H — BANK ACCOUNT DETAILS (pages 20-21)
  // ────────────────────────────────────────────
  {
    id: "bankName",
    questionNumber: 65,
    pageNumber: 10,
    x: 51, y: 427,
    fieldType: "text",
    label: "Bank Name",
    section: "bank",
    lumaQuestion: "What is the name of your bank? For example, Commonwealth Bank, ANZ, Westpac.",
    required: true,
  },
  {
    id: "bsb",
    questionNumber: 66,
    pageNumber: 10,
    x: 50, y: 392,
    fieldType: "text",
    label: "BSB Number",
    section: "bank",
    lumaQuestion: "What is your BSB number? It is a 6-digit number — you can find it on your bank statement or app.",
    required: true,
  },
  {
    id: "accountNumber",
    questionNumber: 67,
    pageNumber: 10,
    x: 51, y: 374,
    fieldType: "text",
    label: "Account Number",
    section: "bank",
    lumaQuestion: "What is your bank account number?",
    required: true,
  },
  {
    id: "accountName",
    questionNumber: 68,
    pageNumber: 10,
    x: 51, y: 338,
    fieldType: "text",
    label: "Account Holder Name",
    section: "bank",
    lumaQuestion: "What name is the bank account in?",
    lumaExplanation: "This is the name shown on the account — it should match your name or be a joint account with your partner.",
    required: true,
    maxWidth: 250,
  },
  {
    id: "accountType",
    questionNumber: 69,
    pageNumber: 10,
    x: 130, y: 610,
    fieldType: "select",
    label: "Account Type",
    section: "bank",
    options: ["Savings", "Cheque"],
    lumaQuestion: "Is this a savings account or a cheque (everyday) account?",
    required: true,
    tickPositions: {
      "Savings": { x: 130, y: 610 },
    },
  },

  // ────────────────────────────────────────────
  // PART I — DECLARATION (pages 33-36)
  // ────────────────────────────────────────────

  // ────────────────────────────────────────────
  // ADDITIONAL QUESTIONS — COMPLETE FORM COVERAGE
  // ────────────────────────────────────────────

  {
    id: "authorisePerson",
    questionNumber: 9,
    pageNumber: 6,
    x: 67, y: 575,
    fieldType: "select",
    label: "Authorise Person",
    section: "personal",
    options: ["Yes", "No"],
    lumaQuestion: "Do you want to authorise someone (like a family member) to deal with Centrelink on your behalf? 👥",
    lumaExplanation: "This is optional. It allows someone you trust to make enquiries, updates or get payments on your behalf.",
    required: false,
    tickPositions: {
      "Yes": { x: 67, y: 575 },
      "No":  { x: 67, y: 591 },
    },
  },
  {
    id: "preferredLanguage",
    questionNumber: 27,
    pageNumber: 11,
    x: 51, y: 463,
    fieldType: "text",
    label: "Preferred Spoken Language",
    section: "residence",
    lumaQuestion: "What is your preferred spoken language? For example: Arabic, Vietnamese, Nepali, Italian, English.",
    lumaExplanation: "This helps Centrelink arrange an interpreter if needed.",
    required: false,
    skipText: "English",
    maxWidth: 250,
    skipIf: { field: "interpreterNeeded", equals: "No", goTo: 28 },
  },
  {
    id: "australianCitizenBornHere",
    questionNumber: 16,
    pageNumber: 11,
    x: 67, y: 62,
    fieldType: "select",
    label: "Australian Citizen Born Here",
    section: "residence",
    options: ["Yes", "No"],
    lumaQuestion: "Were you born in Australia? 🇦🇺",
    required: true,
    tickPositions: {
      "Yes": { x: 67, y: 62 },
      "No":  { x: 67, y: 78 },
    },
    skipIf: { field: "australianCitizen", equals: "No", goTo: 18 },
  },
  {
    id: "countryOfCitizenship",
    questionNumber: 18,
    pageNumber: 11,
    x: 335, y: 447,
    fieldType: "text",
    label: "Country of Citizenship",
    section: "residence",
    lumaQuestion: "What is your country of citizenship?",
    required: false,
    skipText: "Australia",
    maxWidth: 200,
    skipIf: { field: "australianCitizen", equals: "Yes", goTo: 22 },
  },
  {
    id: "relationshipStatus",
    questionNumber: 55,
    pageNumber: 13,
    x: 140, y: 579,
    fieldType: "select",
    label: "Relationship Status",
    section: "partner",
    options: ["Married", "De facto", "Registered relationship"],
    lumaQuestion: "What is your current relationship status with your partner?",
    required: false,
    skipIf: { field: "hasPartner", equals: "No", goTo: 65 },
    tickPositions: {
      "Married":                { x: 140, y: 579 },
      "De facto":               { x: 140, y: 447 },
      "Registered relationship":{ x: 140, y: 512 },
    },
  },
  {
    id: "partnerFamilyName",
    questionNumber: 57,
    pageNumber: 13,
    x: 51, y: 249,
    fieldType: "text",
    label: "Partner Family Name",
    section: "partner",
    lumaQuestion: "What is your partner's family name (surname)?",
    required: false,
    maxWidth: 200,
    skipIf: { field: "hasPartner", equals: "No", goTo: 65 },
  },
  {
    id: "partnerFirstName",
    questionNumber: 57,
    pageNumber: 13,
    x: 51, y: 213,
    fieldType: "text",
    label: "Partner First Name",
    section: "partner",
    lumaQuestion: "What is your partner's first name?",
    required: false,
    maxWidth: 200,
    skipIf: { field: "hasPartner", equals: "No", goTo: 65 },
  },
  {
    id: "partnerGender",
    questionNumber: 61,
    pageNumber: 13,
    x: 379, y: 337,
    fieldType: "select",
    label: "Partner Gender",
    section: "partner",
    options: ["Male", "Female", "Other"],
    lumaQuestion: "What is your partner's gender?",
    required: false,
    skipIf: { field: "hasPartner", equals: "No", goTo: 65 },
    tickPositions: {
      "Male":   { x: 379, y: 337 },
      "Female": { x: 379, y: 321 },
      "Other":  { x: 379, y: 306 },
    },
  },
  {
    id: "partnerAddress",
    questionNumber: 63,
    pageNumber: 13,
    x: 335, y: 192,
    fieldType: "text",
    label: "Partner Address",
    section: "partner",
    lumaQuestion: "What is your partner's permanent address? If same as yours, say 'same'.",
    required: false,
    skipText: "same",
    maxWidth: 350,
    skipIf: { field: "hasPartner", equals: "No", goTo: 65 },
  },
  {
    id: "partnerCountryOfBirth",
    questionNumber: 71,
    pageNumber: 14,
    x: 335, y: 661,
    fieldType: "text",
    label: "Partner Country of Birth",
    section: "partner",
    lumaQuestion: "What is your partner's country of birth?",
    required: false,
    skipText: "Australia",
    maxWidth: 200,
    skipIf: { field: "hasPartner", equals: "No", goTo: 65 },
  },
  {
    id: "accommodationType",
    questionNumber: 86,
    pageNumber: 18,
    x: 501, y: 660,
    fieldType: "select",
    label: "Accommodation Type",
    section: "income",
    options: ["Own home", "Renting privately", "Public housing", "Boarding house", "Living with family", "Aged care home", "Nursing home", "Retirement village", "Other"],
    lumaQuestion: "What best describes where you live? 🏠",
    lumaExplanation: "This helps Centrelink assess your rent assistance eligibility.",
    required: true,
    tickPositions: {
      "Own home":          { x: 501, y: 660 },
      "Renting privately": { x: 501, y: 720 },
      "Public housing":    { x: 501, y: 525 },
      "Boarding house":    { x: 501, y: 488 },
      "Living with family":{ x: 501, y: 660 },
      "Aged care home":    { x: 501, y: 456 },
      "Nursing home":      { x: 501, y: 442 },
      "Retirement village":{ x: 501, y: 425 },
      "Other":             { x: 501, y: 347 },
    },
  },
  {
    id: "conditionCategory",
    questionNumber: 133,
    pageNumber: 29,
    x: 67, y: 763,
    fieldType: "select",
    label: "Condition Category",
    section: "disability",
    options: ["Permanently blind", "Need nursing home care", "Terminal illness", "Intellectual disability", "HIV/AIDS category 4", "None of these"],
    lumaQuestion: "Which of these best describes your condition? A: Permanently blind  B: Need nursing home level care  C: Terminal illness (under 2 years)  D: Intellectual disability (IQ under 70)  E: Category 4 HIV/AIDS. Or say 'none of these'.",
    required: true,
    tickPositions: {
      "Permanently blind":     { x: 67, y: 763 },
      "Need nursing home care":{ x: 67, y: 763 },
      "Terminal illness":      { x: 67, y: 763 },
      "Intellectual disability":{ x: 67, y: 763 },
      "HIV/AIDS category 4":   { x: 67, y: 763 },
      "None of these":         { x: 67, y: 763 },
    },
  },
  {
    id: "currentTreatment",
    questionNumber: 135,
    pageNumber: 31,
    x: 335, y: 462,
    fieldType: "text",
    label: "Current Treatment",
    section: "disability",
    lumaQuestion: "What treatment are you currently receiving for your condition? Include medications, therapy, and appointments. Say 'none' if you are not receiving treatment.",
    lumaExplanation: "Centrelink needs to know your condition is being reasonably treated. This helps them assess your claim.",
    required: true,
    maxWidth: 400,
  },
  {
    id: "pastTreatment",
    questionNumber: 135,
    pageNumber: 31,
    x: 54, y: 113,
    fieldType: "text",
    label: "Past Treatment",
    section: "disability",
    lumaQuestion: "What treatments have you had in the past for your condition?",
    required: false,
    skipText: "none",
    maxWidth: 400,
  },
  {
    id: "futureTreatment",
    questionNumber: 135,
    pageNumber: 31,
    x: 335, y: 94,
    fieldType: "text",
    label: "Future Treatment",
    section: "disability",
    lumaQuestion: "What future treatment is planned for your condition?",
    required: false,
    skipText: "none",
    maxWidth: 400,
  },
  {
    id: "programOfSupport",
    questionNumber: 139,
    pageNumber: 32,
    x: 67, y: 724,
    fieldType: "select",
    label: "Program of Support",
    section: "disability",
    options: ["Yes", "No"],
    lumaQuestion: "Have you participated in a Program of Support (like Workforce Australia or a job training program) in the last 3 years? 📋",
    lumaExplanation: "A Program of Support is a government program that helps people prepare for, find and keep a job. Most DSP claimants need to have done one in the last 3 years.",
    required: true,
    tickPositions: {
      "Yes": { x: 67, y: 724 },
      "No":  { x: 67, y: 740 },
    },
  },
  {
    id: "previousWorkType",
    questionNumber: 137,
    pageNumber: 32,
    x: 58, y: 524,
    fieldType: "text",
    label: "Previous Work Type",
    section: "work",
    lumaQuestion: "What type of work have you done in the last 12 months? If you haven't worked, say 'none'. 💼",
    required: false,
    skipText: "none",
    maxWidth: 250,
  },
  {
    id: "workAffectedByCondition",
    questionNumber: 137,
    pageNumber: 32,
    x: 70, y: 479,
    fieldType: "select",
    label: "Work Affected by Condition",
    section: "work",
    options: ["Yes", "No"],
    lumaQuestion: "Did your condition affect your ability to do that work?",
    required: false,
    skipIf: { field: "previousWorkType", equals: "none", goTo: 70 },
    tickPositions: {
      "Yes": { x: 74, y: 479 },
      "No":  { x: 74, y: 495 },
    },
  },


  // ════════════════════════════════════════════════
  // MISSING QUESTIONS — COMPLETE SA466 COVERAGE
  // Added after deep form audit
  // ════════════════════════════════════════════════

  // Q81 — Share accommodation
  {
    id: "shareAccommodation",
    questionNumber: 81,
    pageNumber: 16,
    x: 67, y: 684,
    fieldType: "select",
    label: "Share Accommodation",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Do you share your home with anyone other than an immediate family member? 🏠",
    lumaExplanation: "An immediate family member is a spouse, partner, child, or parent. This question is about housemates, boarders, or other people living with you.",
    required: true,
    tickPositions: {
      "Yes": { x: 67, y: 684 },
      "No":  { x: 67, y: 700 },
    },
  },

  // Q83 — Own a home not living in
  {
    id: "ownHomeNotLiving",
    questionNumber: 83,
    pageNumber: 18,
    x: 67, y: 750,
    fieldType: "select",
    label: "Own Home Not Living In",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Do you (or your partner) own a home that you are NOT currently living in? 🏡",
    lumaExplanation: "This includes investment properties or a home you own but rent out.",
    required: true,
    tickPositions: {
      "Yes": { x: 67, y: 750 },
      "No":  { x: 67, y: 765 },
    },
  },

  // Q85 — Sold former home
  {
    id: "soldFormerHome",
    questionNumber: 85,
    pageNumber: 18,
    x: 67, y: 469,
    fieldType: "select",
    label: "Sold Former Home",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Have you (or your partner) sold your former home within the last 2 years?",
    required: false,
    skipIf: { field: "ownHomeNotLiving", equals: "No", goTo: 86 },
    tickPositions: {
      "Yes": { x: 67, y: 469 },
      "No":  { x: 67, y: 453 },
    },
  },

  // Q88 — Name on rental contract
  {
    id: "nameOnLease",
    questionNumber: 88,
    pageNumber: 18,
    x: 351, y: 190,
    fieldType: "select",
    label: "Name on Rental Contract",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Is your name (or your partner's name) on the rental contract or lease? 📄",
    required: false,
    skipIf: { field: "accommodationType", equals: "Own home", goTo: 89 },
    tickPositions: {
      "Yes": { x: 351, y: 190 },
      "No":  { x: 351, y: 205 },
    },
  },

  // Q109 — Pay board/lodgings
  {
    id: "payBoardLodgings",
    questionNumber: 109,
    pageNumber: 21,
    x: 350, y: 692,
    fieldType: "select",
    label: "Pay Board or Lodgings",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Do you pay board and/or lodgings where you live?",
    required: false,
    skipIf: { field: "accommodationType", equals: "Own home", goTo: 113 },
    tickPositions: {
      "Yes": { x: 350, y: 692 },
      "No":  { x: 350, y: 707 },
    },
  },

  // Q115 — Formal lease/tenancy
  {
    id: "formalLease",
    questionNumber: 115,
    pageNumber: 22,
    x: 70, y: 565,
    fieldType: "select",
    label: "Formal Lease or Tenancy",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Do you have a formal lease or tenancy agreement? 📋",
    required: false,
    skipIf: { field: "accommodationType", equals: "Own home", goTo: 116 },
    tickPositions: {
      "Yes": { x: 70, y: 565 },
      "No":  { x: 70, y: 581 },
    },
  },

  // Q117 — Income in last 12 months
  {
    id: "incomeLastYear",
    questionNumber: 117,
    pageNumber: 22,
    x: 339, y: 355,
    fieldType: "text",
    label: "Income Last 12 Months",
    section: "income",
    lumaQuestion: "What was your total income in the last 12 months? Include wages, Centrelink, super, interest, rent — everything. If none, say 'none'. 💰",
    required: false,
    skipText: "none",
    maxWidth: 250,
  },

  // Q118 — Redundancy payment
  {
    id: "redundancyPayment",
    questionNumber: 118,
    pageNumber: 23,
    x: 70, y: 565,
    fieldType: "select",
    label: "Redundancy Payment",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Did you (or your partner) receive a redundancy payment in the last 12 months?",
    required: false,
    tickPositions: {
      "Yes": { x: 70, y: 565 },
      "No":  { x: 70, y: 581 },
    },
  },

  // Q120 — Tax file number
  {
    id: "hasTFN",
    questionNumber: 120,
    pageNumber: 23,
    x: 372, y: 619,
    fieldType: "select",
    label: "Has Tax File Number",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Do you have a Tax File Number (TFN)? 🔢",
    lumaExplanation: "Your TFN is a 9-digit number from the ATO. You can find it on your tax return, payment summary, or myGov.",
    required: true,
    tickPositions: {
      "Yes": { x: 372, y: 619 },
      "No":  { x: 372, y: 635 },
    },
  },

  // Q121 — Younger than 21
  {
    id: "youngerThan21",
    questionNumber: 121,
    pageNumber: 23,
    x: 70, y: 432,
    fieldType: "select",
    label: "Younger Than 21",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Are you younger than 21 years old?",
    required: true,
    tickPositions: {
      "Yes": { x: 70, y: 432 },
      "No":  { x: 70, y: 416 },
    },
  },

  // Q124 — Live with parents
  {
    id: "liveWithParents",
    questionNumber: 124,
    pageNumber: 25,
    x: 70, y: 776,
    fieldType: "select",
    label: "Live With Parents",
    section: "income",
    options: ["Yes", "No"],
    lumaQuestion: "Do you currently live with your parent(s)?",
    required: false,
    skipIf: { field: "youngerThan21", equals: "No", goTo: 65 },
    tickPositions: {
      "Yes": { x: 70, y: 776 },
      "No":  { x: 70, y: 792 },
    },
  },

  // Q134 — Specific condition evidence
  {
    id: "specificCondition",
    questionNumber: 134,
    pageNumber: 30,
    x: 557, y: 744,
    fieldType: "select",
    label: "Specific Condition Evidence",
    section: "disability",
    options: ["Eye condition", "Intellectual disability", "HIV/AIDS", "None"],
    lumaQuestion: "Does your condition need specialist evidence? A: Eye condition (not blind but affects vision)  B: Intellectual disability  C: Category 4 HIV/AIDS. Say 'none' if none apply.",
    required: false,
    skipText: "none",
    tickPositions: {
      "Eye condition":       { x: 557, y: 744 },
      "Intellectual disability": { x: 557, y: 552 },
      "HIV/AIDS":           { x: 557, y: 414 },
      "None":               { x: 557, y: 744 },
    },
  },

  // Q136 — Special school
  {
    id: "attendedSpecialSchool",
    questionNumber: 136,
    pageNumber: 32,
    x: 70, y: 724,
    fieldType: "select",
    label: "Attended Special School",
    section: "work",
    options: ["Yes", "No"],
    lumaQuestion: "Have you ever attended a special school or Special Education Unit because of your condition? 🏫",
    lumaExplanation: "Even if this was many years ago, this information helps Centrelink assess your claim.",
    required: false,
    tickPositions: {
      "Yes": { x: 70, y: 724 },
      "No":  { x: 70, y: 740 },
    },
  },

  // Q138 — Extra workplace support
  {
    id: "workplaceSupport",
    questionNumber: 138,
    pageNumber: 32,
    x: 557, y: 724,
    fieldType: "select",
    label: "Extra Workplace Support",
    section: "work",
    options: ["Yes", "No", "None"],
    lumaQuestion: "Did you (or do you) get any extra support in the workplace because of your condition? For example: reduced hours, alternative duties, modified environment, on-the-job support. Say 'none' if not.",
    required: false,
    skipText: "none",
    tickPositions: {
      "Yes":  { x: 557, y: 724 },
      "No":   { x: 557, y: 724 },
      "None": { x: 557, y: 724 },
    },
  },

  // Q142 — Difficulty getting evidence
  {
    id: "difficultyEvidence",
    questionNumber: 142,
    pageNumber: 34,
    x: 70, y: 777,
    fieldType: "select",
    label: "Difficulty Getting Evidence",
    section: "disability",
    options: ["Yes", "No"],
    lumaQuestion: "Are you having difficulty getting the medical evidence Centrelink needs? 📋",
    lumaExplanation: "If yes, Centrelink can help you get the right evidence. Say yes if your doctor is unavailable or if getting evidence is a problem.",
    required: false,
    tickPositions: {
      "Yes": { x: 70, y: 777 },
      "No":  { x: 70, y: 792 },
    },
  },

  // Q77 — Current relationship status (when previously had partner)
  {
    id: "currentRelationshipStatus",
    questionNumber: 77,
    pageNumber: 15,
    x: 424, y: 703,
    fieldType: "select",
    label: "Current Relationship Status",
    section: "partner",
    options: ["Separated", "Divorced", "Widowed", "Never had partner"],
    lumaQuestion: "What is your current relationship status?",
    required: false,
    skipIf: { field: "hasPartner", equals: "Yes", goTo: 57 },
    tickPositions: {
      "Separated":      { x: 424, y: 703 },
      "Divorced":       { x: 424, y: 639 },
      "Widowed":        { x: 424, y: 584 },
      "Never had partner": { x: 424, y: 520 },
    },
  },

  // Partner lived in Australia (Q73)
  {
    id: "partnerLivedInAustralia",
    questionNumber: 73,
    pageNumber: 14,
    x: 350, y: 419,
    fieldType: "select",
    label: "Partner Lived in Australia",
    section: "partner",
    options: ["Yes", "No"],
    lumaQuestion: "Has your partner ever lived in Australia?",
    required: false,
    skipIf: { field: "hasPartner", equals: "No", goTo: 77 },
    tickPositions: {
      "Yes": { x: 350, y: 419 },
      "No":  { x: 350, y: 435 },
    },
  },


  // ════════════════════════════════════════════════
  // REMAINING 28 QUESTIONS — every SA466 question
  // now has a field definition so it CAN be filled
  // ════════════════════════════════════════════════

  // Q11 — Study hours (if studying)
  {
    id: "studyHours", questionNumber: 11, pageNumber: 8,
    x: 52, y: 612, fieldType: "text", label: "Study Hours Per Week",
    section: "work",
    lumaQuestion: "How many hours per week are you studying?",
    required: false, skipText: "none", maxWidth: 80,
    skipIf: { field: "currentlyWorking", equals: "Yes", goTo: 40 },
  },

  // Q22 — Charged with offence
  {
    id: "chargedWithOffence", questionNumber: 22, pageNumber: 8,
    x: 67, y: 207, fieldType: "select", label: "Charged With Offence",
    section: "work", options: ["Yes", "No"],
    lumaQuestion: "Have you been charged with an offence and are currently in custody or on remand?",
    required: false,
    tickPositions: { "Yes": { x: 67, y: 207 }, "No": { x: 67, y: 191 } },
  },

  // Q23 — Institution name
  {
    id: "institutionName", questionNumber: 23, pageNumber: 8,
    x: 334, y: 151, fieldType: "text", label: "Institution Name",
    section: "work",
    lumaQuestion: "What is the name of the institution where you are detained?",
    required: false, skipText: "none", maxWidth: 250,
    skipIf: { field: "chargedWithOffence", equals: "No", goTo: 24 },
  },

  // Q24 — Expected release date
  {
    id: "releaseDate", questionNumber: 24, pageNumber: 8,
    x: 333, y: 301, fieldType: "date", label: "Expected Release Date",
    section: "work",
    lumaQuestion: "What is your expected release date? (DD/MM/YYYY, or say 'unknown')",
    required: false, skipText: "unknown",
    dateBoxes: { ddX: 333, ddY: 301, mmX: 367, mmY: 302, yyyyX: 401, yyyyY: 301 },
    skipIf: { field: "chargedWithOffence", equals: "No", goTo: 25 },
  },

  // Q26 — Claiming Rent Assistance
  {
    id: "claimingRentAssistance", questionNumber: 26, pageNumber: 8,
    x: 350, y: 791, fieldType: "select", label: "Claiming Rent Assistance",
    section: "income", options: ["Yes", "No"],
    lumaQuestion: "Are you (or your partner) claiming Rent Assistance with this application?",
    required: false,
    tickPositions: { "Yes": { x: 350, y: 791 }, "No": { x: 350, y: 775 } },
  },

  // Q27 — Getting NZ payment
  {
    id: "gettingNZPayment", questionNumber: 27, pageNumber: 8,
    x: 350, y: 729, fieldType: "select", label: "Getting NZ Payment",
    section: "income", options: ["Yes", "No"],
    lumaQuestion: "Are you (or your partner) getting a New Zealand payment?",
    required: false,
    tickPositions: { "Yes": { x: 350, y: 729 }, "No": { x: 350, y: 713 } },
  },

  // Q28 — Getting DVA payment
  {
    id: "gettingDVAPayment", questionNumber: 28, pageNumber: 8,
    x: 350, y: 585, fieldType: "select", label: "Getting DVA Payment",
    section: "income", options: ["Yes", "No"],
    lumaQuestion: "Are you (or your partner) getting a payment from the Department of Veterans Affairs (DVA)?",
    required: false,
    tickPositions: { "Yes": { x: 350, y: 585 }, "No": { x: 350, y: 569 } },
  },

  // Q29 — Self-Employment Assistance
  {
    id: "selfEmploymentAssistance", questionNumber: 29, pageNumber: 8,
    x: 350, y: 532, fieldType: "select", label: "Self-Employment Assistance",
    section: "income", options: ["Yes", "No"],
    lumaQuestion: "Are you (or your partner) getting Self-Employment Assistance?",
    required: false,
    tickPositions: { "Yes": { x: 350, y: 532 }, "No": { x: 350, y: 517 } },
  },

  // Q31 — Income stream told before
  {
    id: "incomeStreamToldBefore", questionNumber: 31, pageNumber: 9,
    x: 67, y: 548, fieldType: "select", label: "Income Stream Told Before",
    section: "income", options: ["Yes", "No"],
    lumaQuestion: "Have you (or your partner) told Centrelink about an income stream before?",
    required: false,
    tickPositions: { "Yes": { x: 67, y: 548 }, "No": { x: 67, y: 564 } },
  },

  // Q32 — Getting income stream payments
  {
    id: "gettingIncomeStream", questionNumber: 32, pageNumber: 9,
    x: 67, y: 422, fieldType: "select", label: "Getting Income Stream",
    section: "income", options: ["Yes", "No"],
    lumaQuestion: "Are you (or your partner) getting payments from an income stream product (e.g. superannuation pension, annuity)?",
    required: false,
    tickPositions: { "Yes": { x: 67, y: 422 }, "No": { x: 67, y: 500 } },
  },

  // Q36 — Changes to circumstances
  {
    id: "changedCircumstances", questionNumber: 36, pageNumber: 10,
    x: 350, y: 565, fieldType: "select", label: "Changed Circumstances",
    section: "income", options: ["Yes", "No"],
    lumaQuestion: "Are there any changes to your (or your partner's) financial circumstances that you need to tell us about?",
    required: false,
    tickPositions: { "Yes": { x: 350, y: 565 }, "No": { x: 350, y: 585 } },
  },

  // Q37 — Younger than 21
  {
    id: "under21ForPayment", questionNumber: 37, pageNumber: 10,
    x: 350, y: 485, fieldType: "select", label: "Under 21 For Payment",
    section: "income", options: ["Yes", "No"],
    lumaQuestion: "Are you younger than 21 years old? (This affects your payment rate)",
    required: false,
    tickPositions: { "Yes": { x: 350, y: 485 }, "No": { x: 350, y: 515 } },
  },

  // Q52 — Assurance of support
  {
    id: "assuranceOfSupport", questionNumber: 52, pageNumber: 12,
    x: 84, y: 270, fieldType: "select", label: "Assurance of Support",
    section: "residence", options: ["Yes", "No", "Not sure"],
    lumaQuestion: "Did someone provide you with an assurance of support when you came to Australia?",
    lumaExplanation: "An assurance of support is a legal commitment by a sponsor to support you financially.",
    required: false,
    tickPositions: {
      "Yes": { x: 84, y: 270 }, "No": { x: 84, y: 301 }, "Not sure": { x: 84, y: 286 }
    },
    skipIf: { field: "australianCitizen", equals: "Yes", goTo: 54 },
  },

  // Q59 — Partner authorisation
  {
    id: "partnerAuthorisation", questionNumber: 59, pageNumber: 13,
    x: 350, y: 749, fieldType: "select", label: "Partner Authorisation",
    section: "partner", options: ["Yes", "No"],
    lumaQuestion: "Do you give permission for your partner to speak to Centrelink on your behalf?",
    required: false,
    tickPositions: { "Yes": { x: 350, y: 749 }, "No": { x: 350, y: 765 } },
    skipIf: { field: "hasPartner", equals: "No", goTo: 65 },
  },

  // Q62 — Live with partner
  {
    id: "liveWithPartner", questionNumber: 62, pageNumber: 13,
    x: 350, y: 609, fieldType: "select", label: "Live With Partner",
    section: "partner", options: ["Yes", "No"],
    lumaQuestion: "Do you currently live in the same home as your partner?",
    required: false,
    tickPositions: { "Yes": { x: 350, y: 609 }, "No": { x: 351, y: 624 } },
    skipIf: { field: "hasPartner", equals: "No", goTo: 65 },
  },

  // Q64 — Partner postal address
  {
    id: "partnerPostalAddress", questionNumber: 64, pageNumber: 13,
    x: 335, y: 104, fieldType: "text", label: "Partner Postal Address",
    section: "partner",
    lumaQuestion: "What is your partner's postal address (if different to their permanent address)?",
    required: false, skipText: "same", maxWidth: 350,
    skipIf: { field: "hasPartner", equals: "No", goTo: 65 },
  },

  // Q65 — Why not living with partner
  {
    id: "reasonNotWithPartner", questionNumber: 65, pageNumber: 14,
    x: 135, y: 728, fieldType: "select", label: "Reason Not With Partner",
    section: "partner",
    options: ["Partner illness", "Your illness", "Partner in prison", "Partner employment", "Other"],
    lumaQuestion: "Why are you not living with your partner?",
    required: false,
    tickPositions: {
      "Partner illness":    { x: 135, y: 791 },
      "Your illness":       { x: 135, y: 775 },
      "Partner in prison":  { x: 135, y: 760 },
      "Partner employment": { x: 135, y: 744 },
      "Other":              { x: 135, y: 728 },
    },
    skipIf: { field: "liveWithPartner", equals: "Yes", goTo: 69 },
  },

  // Q68 — Partner's current country
  {
    id: "partnerCurrentCountry", questionNumber: 68, pageNumber: 14,
    x: 350, y: 712, fieldType: "select", label: "Partner Current Country",
    section: "partner", options: ["Australia", "Other"],
    lumaQuestion: "Is your partner currently living in Australia?",
    required: false,
    tickPositions: { "Australia": { x: 371, y: 612 }, "Other": { x: 371, y: 554 } },
    skipIf: { field: "liveWithPartner", equals: "Yes", goTo: 69 },
  },

  // Q69 — Partner travelled overseas
  {
    id: "partnerTravelledOverseas", questionNumber: 69, pageNumber: 14,
    x: 350, y: 419, fieldType: "select", label: "Partner Travelled Overseas",
    section: "partner", options: ["Yes", "No"],
    lumaQuestion: "Has your partner ever travelled outside Australia, including short trips?",
    required: false,
    tickPositions: { "Yes": { x: 350, y: 419 }, "No": { x: 350, y: 435 } },
    skipIf: { field: "hasPartner", equals: "No", goTo: 77 },
  },

  // Q72 — Partner Australian citizen
  {
    id: "partnerAustralianCitizen", questionNumber: 72, pageNumber: 14,
    x: 371, y: 612, fieldType: "select", label: "Partner Australian Citizen",
    section: "partner", options: ["Yes", "No"],
    lumaQuestion: "Is your partner an Australian citizen?",
    required: false,
    tickPositions: { "Yes": { x: 371, y: 612 }, "No": { x: 371, y: 554 } },
    skipIf: { field: "hasPartner", equals: "No", goTo: 77 },
  },

  // Q74 — Partner visa type
  {
    id: "partnerVisaType", questionNumber: 74, pageNumber: 14,
    x: 422, y: 358, fieldType: "select", label: "Partner Visa Type",
    section: "partner", options: ["Permanent", "Temporary", "New Zealand", "Not sure"],
    lumaQuestion: "What type of visa does your partner have?",
    required: false,
    tickPositions: {
      "Permanent": { x: 422, y: 374 }, "Temporary": { x: 422, y: 358 },
      "New Zealand": { x: 421, y: 342 }, "Not sure": { x: 421, y: 315 },
    },
    skipIf: { field: "partnerAustralianCitizen", equals: "Yes", goTo: 77 },
  },

  // Q84 — Why not in own home
  {
    id: "whyNotInOwnHome", questionNumber: 84, pageNumber: 18,
    x: 180, y: 693, fieldType: "select", label: "Why Not In Own Home",
    section: "income",
    options: ["Study", "Medical treatment", "Receiving care", "Providing care", "Overseas", "Other"],
    lumaQuestion: "Why are you not living in your own home?",
    required: false,
    skipIf: { field: "ownHomeNotLiving", equals: "No", goTo: 85 },
    tickPositions: {
      "Study":            { x: 180, y: 693 },
      "Medical treatment":{ x: 180, y: 678 },
      "Receiving care":   { x: 180, y: 662 },
      "Providing care":   { x: 180, y: 618 },
      "Overseas":         { x: 180, y: 599 },
      "Other":            { x: 180, y: 583 },
    },
  },

  // Q87 — Site or mooring fees
  {
    id: "siteMooringFees", questionNumber: 87, pageNumber: 18,
    x: 351, y: 114, fieldType: "select", label: "Site or Mooring Fees",
    section: "income", options: ["Yes", "No"],
    lumaQuestion: "Do you pay site or mooring fees (e.g. for a caravan or boat)?",
    required: false,
    skipIf: { field: "accommodationType", equals: "Own home", goTo: 88 },
    tickPositions: { "Yes": { x: 351, y: 114 }, "No": { x: 351, y: 130 } },
  },

  // Q89 — Primary tenant market rate
  {
    id: "primaryTenantMarketRate", questionNumber: 89, pageNumber: 19,
    x: 84, y: 763, fieldType: "select", label: "Primary Tenant Market Rate",
    section: "income", options: ["Yes", "No", "Not sure"],
    lumaQuestion: "Is the primary tenant paying the market rate of rent?",
    required: false,
    skipIf: { field: "nameOnLease", equals: "Yes", goTo: 90 },
    tickPositions: {
      "Yes": { x: 84, y: 763 }, "No": { x: 84, y: 794 }, "Not sure": { x: 84, y: 778 }
    },
  },

  // Q91 — Name of aged care home
  {
    id: "agedCareHomeName", questionNumber: 91, pageNumber: 19,
    x: 51, y: 577, fieldType: "text", label: "Aged Care Home Name",
    section: "income",
    lumaQuestion: "What is the name of the aged care home or nursing home you live in?",
    required: false, skipText: "none", maxWidth: 250,
    skipIf: { field: "accommodationType", equals: "Own home", goTo: 92 },
  },

  // Q92 — Date moved in (aged care)
  {
    id: "agedCareMoveInDate", questionNumber: 92, pageNumber: 19,
    x: 49, y: 508, fieldType: "date", label: "Aged Care Move-in Date",
    section: "income",
    lumaQuestion: "What date did you move into the aged care home? (DD/MM/YYYY)",
    required: false,
    dateBoxes: { ddX: 49, ddY: 508, mmX: 84, mmY: 508, yyyyX: 118, yyyyY: 508 },
    skipIf: { field: "accommodationType", equals: "Own home", goTo: 93 },
  },

  // Q93 — How long staying
  {
    id: "howLongStaying", questionNumber: 93, pageNumber: 19,
    x: 70, y: 408, fieldType: "select", label: "How Long Staying",
    section: "income", options: ["Long term", "Short term"],
    lumaQuestion: "How long will you be staying in the aged care home? Long term (permanent) or short term (respite/temporary)?",
    required: false,
    tickPositions: { "Long term": { x: 70, y: 408 }, "Short term": { x: 70, y: 371 } },
    skipIf: { field: "agedCareHomeName", equals: "none", goTo: 94 },
  },

  // Q96 — Gift/loan in addition to entry fee
  {
    id: "giftLoanEntryFee", questionNumber: 96, pageNumber: 19,
    x: 350, y: 564, fieldType: "select", label: "Gift/Loan Entry Fee",
    section: "income", options: ["Yes", "No"],
    lumaQuestion: "Did you (or your partner) make a gift or loan in addition to the entry contribution for your accommodation?",
    required: false,
    tickPositions: { "Yes": { x: 350, y: 564 }, "No": { x: 350, y: 580 } },
    skipIf: { field: "accommodationType", equals: "Own home", goTo: 97 },
  },

  // Q99 — Paid entry contribution
  {
    id: "paidEntryContribution", questionNumber: 99, pageNumber: 20,
    x: 70, y: 707, fieldType: "select", label: "Paid Entry Contribution",
    section: "income", options: ["Yes", "No"],
    lumaQuestion: "Did you (or your partner) pay an entry contribution for your accommodation (e.g. for an aged care home)?",
    required: false,
    tickPositions: { "Yes": { x: 70, y: 707 }, "No": { x: 70, y: 723 } },
    skipIf: { field: "accommodationType", equals: "Own home", goTo: 100 },
  },

  // Q102 — Sold / transferred assets
  {
    id: "soldOrTransferredAssets", questionNumber: 102, pageNumber: 20,
    x: 70, y: 348, fieldType: "select", label: "Sold or Transferred Assets",
    section: "income", options: ["Yes", "No"],
    lumaQuestion: "Have you (or your partner) sold, gifted, or transferred any assets (money, property, shares) in the last 5 years for less than their value?",
    lumaExplanation: "This is called 'deprivation of assets'. Centrelink may still count these assets in your means test.",
    required: false,
    tickPositions: { "Yes": { x: 70, y: 348 }, "No": { x: 70, y: 364 } },
  },

  // Q111 — Board/lodgings amount
  {
    id: "boardLodgingsAmount", questionNumber: 111, pageNumber: 21,
    x: 381, y: 602, fieldType: "text", label: "Board/Lodgings Amount",
    section: "income",
    lumaQuestion: "How much do you pay per week for board and/or lodgings? (e.g. '250' for $250 per week)",
    required: false, skipText: "none", maxWidth: 120,
    skipIf: { field: "payBoardLodgings", equals: "No", goTo: 113 },
  },

  // Q113 — Accommodation type (boarding subtype)
  {
    id: "boardingSubtype", questionNumber: 113, pageNumber: 21,
    x: 472, y: 165, fieldType: "select", label: "Boarding Subtype",
    section: "income",
    options: ["Boarding house", "Private", "Community", "Defence", "Caravan", "Boat", "Other"],
    lumaQuestion: "What type of accommodation do you live in?",
    required: false,
    tickPositions: {
      "Boarding house": { x: 472, y: 205 }, "Private":    { x: 472, y: 180 },
      "Community":      { x: 472, y: 165 }, "Defence":    { x: 472, y: 149 },
      "Caravan":        { x: 472, y: 134 }, "Boat":       { x: 472, y: 118 },
      "Other":          { x: 472, y: 102 },
    },
    skipIf: { field: "payBoardLodgings", equals: "No", goTo: 114 },
  },

  // Q114 — Total amount charged
  {
    id: "totalAmountCharged", questionNumber: 114, pageNumber: 22,
    x: 348, y: 480, fieldType: "text", label: "Total Amount Charged",
    section: "income",
    lumaQuestion: "What is the total amount you are charged per week for your accommodation (board, lodging, and any meals)?",
    required: false, skipText: "none", maxWidth: 120,
    skipIf: { field: "payBoardLodgings", equals: "No", goTo: 115 },
  },

  // Q116 — Income in last 12 months (employment)
  {
    id: "employerLastYear", questionNumber: 116, pageNumber: 22,
    x: 339, y: 355, fieldType: "text", label: "Employer Last Year",
    section: "work",
    lumaQuestion: "What was the name of your employer in the last 12 months? If you didn't work, say 'none'.",
    required: false, skipText: "none", maxWidth: 250,
  },


  // Q74 — Partner visa type (already added above as partnerVisaType Q74)
  // Q75 — Partner current visa details
  {
    id: "partnerCurrentVisa", questionNumber: 75, pageNumber: 14,
    x: 334, y: 252, fieldType: "text", label: "Partner Current Visa",
    section: "partner",
    lumaQuestion: "What is your partner's current visa class or subclass number? (e.g. '309', '820', 'permanent'). Say 'not sure' if unknown.",
    required: false, skipText: "not sure",
    skipIf: { field: "partnerAustralianCitizen", equals: "Yes", goTo: 77 },
  },

  // Q78 — Deceased partner details
  {
    id: "deceasedPartnerName", questionNumber: 78, pageNumber: 15,
    x: 340, y: 439, fieldType: "text", label: "Deceased Partner Name",
    section: "partner",
    lumaQuestion: "What was your deceased partner's full name?",
    required: false, skipText: "none",
    skipIf: { field: "currentRelationshipStatus", equals: "Separated", goTo: 81 },
  },

  // Q79 — Ex-partner family name
  {
    id: "exPartnerFamilyName", questionNumber: 79, pageNumber: 15,
    x: 335, y: 333, fieldType: "text", label: "Ex-Partner Family Name",
    section: "partner",
    lumaQuestion: "What is your ex-partner's family name?",
    required: false, skipText: "none",
    skipIf: { field: "hasPartner", equals: "Yes", goTo: 81 },
  },

  // Q80 — Ex-partner address
  {
    id: "exPartnerAddress", questionNumber: 80, pageNumber: 15,
    x: 335, y: 208, fieldType: "text", label: "Ex-Partner Address",
    section: "partner",
    lumaQuestion: "What is your ex-partner's current address (if known)? Say 'unknown' if you don't know.",
    required: false, skipText: "unknown",
    skipIf: { field: "hasPartner", equals: "Yes", goTo: 81 },
  },

  // Q90 — Live with primary tenant
  {
    id: "liveWithPrimaryTenant", questionNumber: 90, pageNumber: 19,
    x: 67, y: 676, fieldType: "select", label: "Live With Primary Tenant",
    section: "income", options: ["Yes", "No"],
    lumaQuestion: "Do you live with the primary tenant in their home?",
    required: false,
    tickPositions: { "Yes": { x: 67, y: 676 }, "No": { x: 67, y: 692 } },
    skipIf: { field: "nameOnLease", equals: "Yes", goTo: 91 },
  },

  // Q97 — Gift/loan amount (aged care)
  {
    id: "giftLoanAmount", questionNumber: 97, pageNumber: 19,
    x: 344, y: 367, fieldType: "text", label: "Gift/Loan Amount",
    section: "income",
    lumaQuestion: "What was the additional gift or loan amount? (e.g. '$50,000')",
    required: false, skipText: "none", maxWidth: 120,
    skipIf: { field: "giftLoanEntryFee", equals: "No", goTo: 99 },
  },

  // Q98 — Date moved in (aged care)
  {
    id: "entryContributionMoveDate", questionNumber: 98, pageNumber: 19,
    x: 331, y: 203, fieldType: "date", label: "Entry Contribution Move Date",
    section: "income",
    lumaQuestion: "What date did you pay the entry contribution? (DD/MM/YYYY)",
    required: false,
    dateBoxes: { ddX: 331, ddY: 203, mmX: 365, mmY: 203, yyyyX: 399, yyyyY: 203 },
    skipIf: { field: "paidEntryContribution", equals: "No", goTo: 100 },
  },

  {
    id: "declarationDate",
    questionNumber: 70,
    pageNumber: 33,
    x: 130, y: 300,
    fieldType: "date",
    label: "Declaration Date",
    section: "declaration",
    lumaQuestion: "Today's date will be used for the declaration. Shall I use today's date?",
    lumaExplanation: "This is the date you are signing and submitting this form.",
    required: true,
    dateBoxes: { ddX: 130, ddY: 300, mmX: 165, mmY: 300, yyyyX: 200, yyyyY: 300 },
  },
  {
    id: "declarationSignature",
    questionNumber: 71,
    pageNumber: 33,
    x: 130, y: 260,
    fieldType: "text",
    label: "Signature",
    section: "declaration",
    lumaQuestion: "Almost done! ✍️",
    signatureNotice: "You will need to sign this section by hand after you print the form. Just write your signature in the box on the last page.",
    required: false,
  },
  {
    id: "declarationComplete",
    questionNumber: 72,
    pageNumber: 33,
    x: 0, y: 0,
    fieldType: "text",
    label: "Confirmation",
    section: "declaration",
    lumaQuestion: "You have completed the entire form! 🎉 Your Disability Support Pension form is ready to download, print, sign, and post to Centrelink at: Reply Paid 7800, Canberra BC ACT 2610.",
    required: false,
  },
];
