import { useState } from "react";
import { useSearchParams, useNavigate } from "react-router-dom";
import { SERVICES, getServiceBySlug } from "@/data/services";
import TopBar from "@/components/landing/TopBar";
import StickyNav from "@/components/landing/StickyNav";
import Footer from "@/components/landing/Footer";
import LumaAvatar from "@/components/landing/LumaAvatar";
import { useLanguage } from "@/contexts/LanguageContext";
import { jsPDF } from "jspdf";

const nameKeys: Record<string, string> = {
  "disability-support": "service.dsp",
  "medicare": "service.medicare",
  "ndis-access": "service.ndis",
  "aged-care": "service.agedCare",
  "carer-payment": "service.carer",
  "age-pension": "service.agePension",
};

const PrepareForm = () => {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const { t, dir } = useLanguage();
  const preselected = searchParams.get("service") || "";

  const [selectedService, setSelectedService] = useState(preselected);
  const [step, setStep] = useState<"select" | "upload" | "confirm" | "done">(preselected ? "upload" : "select");
  const [name, setName] = useState("");
  const [medicareFile, setMedicareFile] = useState<File | null>(null);
  const [idFile, setIdFile] = useState<File | null>(null);

  const service = getServiceBySlug(selectedService);
  const serviceName = service ? t(nameKeys[selectedService] || service.name) : "";

  const handleSelectService = (slug: string) => {
    setSelectedService(slug);
    setStep("upload");
  };

  const handleConfirm = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) return;
    setStep("confirm");
  };

  const generatePDF = (e: React.MouseEvent) => {
    e.preventDefault();
    const doc = new jsPDF();
    const today = new Date().toLocaleDateString("en-AU");
    doc.setFontSize(18);
    doc.text("Northern Community Care SA Inc", 20, 25);
    doc.setFontSize(11);
    doc.text("Pre-filled Form Summary", 20, 34);
    doc.line(20, 37, 190, 37);
    doc.setFontSize(12);
    doc.text(`Date: ${today}`, 20, 48);
    doc.text(`Full Name: ${name}`, 20, 58);
    doc.text(`Form Type: ${serviceName}`, 20, 68);
    doc.text(`Medicare Card: ${medicareFile ? "Provided" : "Not provided"}`, 20, 78);
    doc.text(`ID Document: ${idFile ? "Provided" : "Not provided"}`, 20, 88);
    doc.setFontSize(10);
    doc.text("This summary was generated by Luma at NCCSA.", 20, 110);
    doc.text("Please bring this to your appointment or post it to the address below.", 20, 118);
    doc.text("Northern Community Care SA Inc, Northern Adelaide, SA", 20, 128);
    doc.save(`NCCSA-${selectedService}-${today}.pdf`);
    setStep("done");
  };

  return (
    <div className="min-h-screen bg-background" dir={dir}>
      <TopBar />
      <StickyNav />
      <main className="mx-auto max-w-2xl px-4 py-10">
        <button onClick={(e) => { e.preventDefault(); navigate("/"); }} className="mb-6 text-sm font-semibold text-primary hover:underline">
          {t("service.back")}
        </button>

        <div className="mb-8 text-center">
          <h1 className="font-serif text-3xl font-extrabold text-foreground">{t("prepare.title")}</h1>
          <p className="mt-2 text-base text-muted-foreground">{t("prepare.desc")}</p>
        </div>

        {step === "select" && (
          <div className="space-y-3">
            <div className="flex items-start gap-3 mb-4">
              <LumaAvatar size={32} />
              <div className="rounded-2xl border border-border bg-secondary px-4 py-3 text-sm text-foreground">{t("prepare.whichForm")}</div>
            </div>
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
              {SERVICES.map((s) => (
                <button key={s.slug} onClick={(e) => { e.preventDefault(); handleSelectService(s.slug); }} className="card-hover relative rounded-[14px] border border-border bg-card p-4 text-left transition-all hover:border-primary">
                  <span className="text-2xl">{s.icon}</span>
                  <div className="mt-1 font-serif text-sm font-bold text-foreground">{t(nameKeys[s.slug] || s.name)}</div>
                  <div className="mt-1 text-xs font-semibold text-primary">{t("prepare.select")}</div>
                </button>
              ))}
            </div>
          </div>
        )}

        {step === "upload" && service && (
          <div className="space-y-4">
            <div className="flex items-start gap-3">
              <LumaAvatar size={32} />
              <div className="rounded-2xl border border-border bg-secondary px-4 py-3 text-sm text-foreground">
                {t("prepare.desc")} — <strong>{serviceName}</strong>
              </div>
            </div>
            <div className="space-y-4 rounded-2xl border border-border bg-card p-5">
              <div>
                <label className="mb-1 block text-sm font-bold text-foreground">{t("prepare.fullName")}</label>
                <input value={name} onChange={(e) => setName(e.target.value)} placeholder={t("prepare.enterName")} className="w-full rounded-xl border border-border bg-background px-4 py-2.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/30" />
              </div>
              <div>
                <label className="mb-1 block text-sm font-bold text-foreground">{t("prepare.medicareCard")}</label>
                <input type="file" accept="image/*" capture="environment" onChange={(e) => setMedicareFile(e.target.files?.[0] || null)} className="w-full rounded-xl border border-border bg-background px-4 py-2.5 text-sm text-foreground file:mr-3 file:rounded-lg file:border-0 file:bg-primary file:px-3 file:py-1 file:text-xs file:font-bold file:text-primary-foreground" />
                {medicareFile && <p className="mt-1 text-xs text-primary">✓ {medicareFile.name}</p>}
              </div>
              <div>
                <label className="mb-1 block text-sm font-bold text-foreground">{t("prepare.idDoc")}</label>
                <input type="file" accept="image/*" capture="environment" onChange={(e) => setIdFile(e.target.files?.[0] || null)} className="w-full rounded-xl border border-border bg-background px-4 py-2.5 text-sm text-foreground file:mr-3 file:rounded-lg file:border-0 file:bg-primary file:px-3 file:py-1 file:text-xs file:font-bold file:text-primary-foreground" />
                {idFile && <p className="mt-1 text-xs text-primary">✓ {idFile.name}</p>}
              </div>
              <button onClick={handleConfirm} disabled={!name.trim()} className="w-full rounded-xl bg-primary py-3 text-sm font-bold text-primary-foreground transition-all hover:bg-forest-hover disabled:opacity-50">{t("prepare.continue")}</button>
            </div>
          </div>
        )}

        {step === "confirm" && service && (
          <div className="space-y-4">
            <div className="flex items-start gap-3">
              <LumaAvatar size={32} />
              <div className="rounded-2xl border border-border bg-secondary px-4 py-3 text-sm text-foreground">{t("prepare.gotDetails")}</div>
            </div>
            <div className="rounded-2xl border border-border bg-card p-5 space-y-2">
              <div className="flex justify-between text-sm"><span className="text-muted-foreground">{t("prepare.name")}</span><span className="font-bold text-foreground">{name}</span></div>
              <div className="flex justify-between text-sm"><span className="text-muted-foreground">{t("prepare.form")}</span><span className="font-bold text-foreground">{serviceName}</span></div>
              <div className="flex justify-between text-sm"><span className="text-muted-foreground">{t("prepare.medicareCard")}</span><span className="font-bold text-primary">{medicareFile ? t("prepare.uploaded") : t("prepare.notProvided")}</span></div>
              <div className="flex justify-between text-sm"><span className="text-muted-foreground">{t("prepare.idDoc")}</span><span className="font-bold text-primary">{idFile ? t("prepare.uploaded") : t("prepare.notProvided")}</span></div>
              <div className="flex justify-between text-sm"><span className="text-muted-foreground">{t("prepare.date")}</span><span className="font-bold text-foreground">{new Date().toLocaleDateString("en-AU")}</span></div>
            </div>
            <button onClick={generatePDF} className="w-full rounded-xl bg-primary py-3 text-sm font-bold text-primary-foreground transition-all hover:bg-forest-hover">{t("prepare.download")}</button>
            <p className="text-center text-xs text-muted-foreground">{t("prepare.docsLocal")}</p>
          </div>
        )}

        {step === "done" && (
          <div className="space-y-4 text-center">
            <div className="flex items-start gap-3 justify-center">
              <LumaAvatar size={32} />
              <div className="rounded-2xl border border-border bg-secondary px-4 py-3 text-sm text-foreground">{t("prepare.done")}</div>
            </div>
            <button onClick={(e) => { e.preventDefault(); navigate("/"); }} className="rounded-xl border border-border bg-card px-6 py-3 text-sm font-bold text-foreground hover:bg-muted transition-colors">{t("prepare.backHome")}</button>
          </div>
        )}
      </main>
      <Footer />
    </div>
  );
};

export default PrepareForm;
