import { useState } from "react";
import { useSearchParams, useNavigate } from "react-router-dom";
import { SERVICES, getServiceBySlug } from "@/data/services";
import TopBar from "@/components/landing/TopBar";
import StickyNav from "@/components/landing/StickyNav";
import Footer from "@/components/landing/Footer";
import LumaAvatar from "@/components/landing/LumaAvatar";
import { jsPDF } from "jspdf";

const PrepareForm = () => {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const preselected = searchParams.get("service") || "";

  const [selectedService, setSelectedService] = useState(preselected);
  const [step, setStep] = useState<"select" | "upload" | "confirm" | "done">(preselected ? "upload" : "select");
  const [name, setName] = useState("");
  const [medicareFile, setMedicareFile] = useState<File | null>(null);
  const [idFile, setIdFile] = useState<File | null>(null);

  const service = getServiceBySlug(selectedService);

  const handleSelectService = (slug: string) => {
    setSelectedService(slug);
    setStep("upload");
  };

  const handleConfirm = () => {
    if (!name.trim()) return;
    setStep("confirm");
  };

  const generatePDF = () => {
    const doc = new jsPDF();
    const today = new Date().toLocaleDateString("en-AU");

    doc.setFontSize(18);
    doc.text("Northern Community Care SA Inc", 20, 25);
    doc.setFontSize(11);
    doc.text("Pre-filled Form Summary", 20, 34);
    doc.line(20, 37, 190, 37);

    doc.setFontSize(12);
    doc.text(`Date: ${today}`, 20, 48);
    doc.text(`Full Name: ${name}`, 20, 58);
    doc.text(`Form Type: ${service?.name || selectedService}`, 20, 68);
    doc.text(`Medicare Card: ${medicareFile ? "Provided" : "Not provided"}`, 20, 78);
    doc.text(`ID Document: ${idFile ? "Provided" : "Not provided"}`, 20, 88);

    doc.setFontSize(10);
    doc.text("This summary was generated by Luma at NCCSA.", 20, 110);
    doc.text("Please bring this to your appointment or post it to the address below.", 20, 118);
    doc.text("Northern Community Care SA Inc, Northern Adelaide, SA", 20, 128);

    doc.save(`NCCSA-${selectedService}-${today}.pdf`);
    setStep("done");
  };

  return (
    <div className="min-h-screen bg-background">
      <TopBar />
      <StickyNav />
      <main className="mx-auto max-w-2xl px-4 py-10">
        <button onClick={() => navigate("/")} className="mb-6 text-sm font-semibold text-primary hover:underline">
          ← Back to all services
        </button>

        <div className="mb-8 text-center">
          <h1 className="font-serif text-3xl font-extrabold text-foreground">Prepare Your Form</h1>
          <p className="mt-2 text-base text-muted-foreground">
            Luma will help you get your documents ready.
          </p>
        </div>

        {/* Step 1: Select service */}
        {step === "select" && (
          <div className="space-y-3">
            <div className="flex items-start gap-3 mb-4">
              <LumaAvatar size={32} />
              <div className="rounded-2xl border border-border bg-secondary px-4 py-3 text-sm text-foreground">
                Which form do you need? Pick one below.
              </div>
            </div>
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
              {SERVICES.map((s) => (
                <button
                  key={s.slug}
                  onClick={() => handleSelectService(s.slug)}
                  className="card-hover relative rounded-[14px] border border-border bg-card p-4 text-left transition-all hover:border-primary"
                >
                  <span className="text-2xl">{s.icon}</span>
                  <div className="mt-1 font-serif text-sm font-bold text-foreground">{s.name}</div>
                  <div className="mt-1 text-xs font-semibold text-primary">Select →</div>
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Step 2: Upload documents */}
        {step === "upload" && service && (
          <div className="space-y-4">
            <div className="flex items-start gap-3">
              <LumaAvatar size={32} />
              <div className="rounded-2xl border border-border bg-secondary px-4 py-3 text-sm text-foreground">
                Great — preparing <strong>{service.name}</strong>. Please enter your full name, then upload or photograph your Medicare card and one ID document.
              </div>
            </div>

            <div className="space-y-4 rounded-2xl border border-border bg-card p-5">
              <div>
                <label className="mb-1 block text-sm font-bold text-foreground">Full Name</label>
                <input
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="Enter your full name"
                  className="w-full rounded-xl border border-border bg-background px-4 py-2.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
                />
              </div>

              <div>
                <label className="mb-1 block text-sm font-bold text-foreground">Medicare Card (photo or scan)</label>
                <input
                  type="file"
                  accept="image/*"
                  capture="environment"
                  onChange={(e) => setMedicareFile(e.target.files?.[0] || null)}
                  className="w-full rounded-xl border border-border bg-background px-4 py-2.5 text-sm text-foreground file:mr-3 file:rounded-lg file:border-0 file:bg-primary file:px-3 file:py-1 file:text-xs file:font-bold file:text-primary-foreground"
                />
                {medicareFile && <p className="mt-1 text-xs text-primary">✓ {medicareFile.name}</p>}
              </div>

              <div>
                <label className="mb-1 block text-sm font-bold text-foreground">ID Document (passport, licence, etc.)</label>
                <input
                  type="file"
                  accept="image/*"
                  capture="environment"
                  onChange={(e) => setIdFile(e.target.files?.[0] || null)}
                  className="w-full rounded-xl border border-border bg-background px-4 py-2.5 text-sm text-foreground file:mr-3 file:rounded-lg file:border-0 file:bg-primary file:px-3 file:py-1 file:text-xs file:font-bold file:text-primary-foreground"
                />
                {idFile && <p className="mt-1 text-xs text-primary">✓ {idFile.name}</p>}
              </div>

              <button
                onClick={handleConfirm}
                disabled={!name.trim()}
                className="w-full rounded-xl bg-primary py-3 text-sm font-bold text-primary-foreground transition-all hover:bg-forest-hover disabled:opacity-50"
              >
                Continue →
              </button>
            </div>
          </div>
        )}

        {/* Step 3: Confirm */}
        {step === "confirm" && service && (
          <div className="space-y-4">
            <div className="flex items-start gap-3">
              <LumaAvatar size={32} />
              <div className="rounded-2xl border border-border bg-secondary px-4 py-3 text-sm text-foreground">
                I've got your details. Here's what I found:
              </div>
            </div>

            <div className="rounded-2xl border border-border bg-card p-5 space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Name</span>
                <span className="font-bold text-foreground">{name}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Form</span>
                <span className="font-bold text-foreground">{service.name}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Medicare Card</span>
                <span className="font-bold text-primary">{medicareFile ? "✓ Uploaded" : "Not provided"}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">ID Document</span>
                <span className="font-bold text-primary">{idFile ? "✓ Uploaded" : "Not provided"}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Date</span>
                <span className="font-bold text-foreground">{new Date().toLocaleDateString("en-AU")}</span>
              </div>
            </div>

            <button
              onClick={generatePDF}
              className="w-full rounded-xl bg-primary py-3 text-sm font-bold text-primary-foreground transition-all hover:bg-forest-hover"
            >
              Download my pre-filled form →
            </button>

            <p className="text-center text-xs text-muted-foreground">
              🔒 Your documents are processed locally and never stored on our servers.
            </p>
          </div>
        )}

        {/* Step 4: Done */}
        {step === "done" && (
          <div className="space-y-4 text-center">
            <div className="flex items-start gap-3 justify-center">
              <LumaAvatar size={32} />
              <div className="rounded-2xl border border-border bg-secondary px-4 py-3 text-sm text-foreground">
                Your form has been downloaded! Print it and post it, or bring it to our office. You're all set!
              </div>
            </div>
            <button
              onClick={() => navigate("/")}
              className="rounded-xl border border-border bg-card px-6 py-3 text-sm font-bold text-foreground hover:bg-muted transition-colors"
            >
              ← Back to home
            </button>
          </div>
        )}
      </main>
      <Footer />
    </div>
  );
};

export default PrepareForm;
